MODULE NURBS_PU

	USE GLBVAR
	USE PATCH_MAPPING

	IMPLICIT INTEGER (I-N)
	IMPLICIT REAL(8) (A-H,O-Z)

CONTAINS

! !!  FIND DERIVATIVES OF NURBS SURFACE ON TWO-DIMENSIONAL SPACE
! !!  INPUT  : PT - POINT, KVEC - A VALID KNOT VECTOR, DIFF_ORDER - ORDER OF DIFFERENTIATION
! !!  OUTPUT : DERIVATIVES OF NURBS SURFACE
! SUBROUTINE GET_ALL_PHY_NURBS_SURFACE_2D(SF, INDX, REF_PT, JACOB)
! 
! 	TYPE(FVALUE), INTENT(OUT) :: SF((BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1))
! 	TYPE(INT2D), INTENT(OUT) :: INDX((BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1))
! 	TYPE(POINT2D), INTENT(IN) :: REF_PT
! 	TYPE(MATRIX_22), INTENT(IN) :: JACOB
! 
! 	TYPE(SECOND_PARTIAL_DERIVATIVES) :: SECOND_PD
! 	TYPE(MATRIX_22) :: INV_JACOB, JACOBIAN
! 	TYPE(FUNCTION_2D) :: DIFF_NURBS
! 	TYPE(DIFF_BSPLINES) :: DBSFUN(2)
! 	REAL(8) :: DWSUM(0:MAX_DIFF_ORDER,0:MAX_DIFF_ORDER), J, JXI, JETA, S(2,3)
! 	INTEGER :: INDX_X, INDX_Y, DIFF_ORDER
! 	INTEGER :: I, K, L, J1, J2, I1, I2, LC_INDX
! 
! 	DIFF_ORDER = 2
! 
! 	INV_JACOB = .INVERSE.JACOB					!! P(XI)/P(X), P(XI)/P(Y) // P(ETA)/P(X), P(ETA)/P(Y)
! 
! ! 	ELSE
! ! 		JACOBIAN = GET_JACOBIAN_MATRIX(REF_PT,PATCH)			!! P(X)/P(XI), P(X)/P(ETA) // P(Y)/P(XI), P(Y)/P(ETA)
! ! 		INV_JACOB = .INVERSE.JACOBIAN					!! P(XI)/P(X), P(XI)/P(Y) // P(ETA)/P(X), P(ETA)/P(Y)
! ! 	ENDIF
! 	
! 	
! 	SECOND_PD = GET_PARTIAL(REF_PT)				!! P^2(X)/P(XI^2), P^2(X)/P(XI,ETA), P^2(X)/P(ETA^2), P^2(Y)/P(XI^2), P^2(Y)/P(XI,ETA), P^2(Y)/P(ETA^2)
! 	
!  	J = JACOB%ENT(1,1)*JACOB%ENT(2,2)-JACOB%ENT(1,2)*JACOB%ENT(2,1)
! 	JXI = SECOND_PD%X(1)*JACOB%ENT(2,2)+JACOB%ENT(1,1)*SECOND_PD%Y(2)-SECOND_PD%X(2)*JACOB%ENT(2,1)-JACOB%ENT(1,2)*SECOND_PD%Y(1)
! 	JETA = SECOND_PD%X(2)*JACOB%ENT(2,2)+JACOB%ENT(1,1)*SECOND_PD%Y(3)-SECOND_PD%X(3)*JACOB%ENT(2,1)-JACOB%ENT(1,2)*SECOND_PD%Y(2)
! 	
! 	S(1,1) = -(JXI*JACOB%ENT(2,2)*JACOB%ENT(2,2)-JETA*JACOB%ENT(2,1)*JACOB%ENT(2,2))/J**3+(SECOND_PD%Y(2)*JACOB%ENT(2,2)-SECOND_PD%Y(3)*JACOB%ENT(2,1))/J**2
! 	S(1,2) = (JXI*JACOB%ENT(1,2)*JACOB%ENT(2,2)-JETA*JACOB%ENT(1,2)*JACOB%ENT(2,1))/J**3-(SECOND_PD%X(2)*JACOB%ENT(2,2)-SECOND_PD%X(3)*JACOB%ENT(2,1))/J**2
! 	S(1,3) = -(JXI*JACOB%ENT(1,2)*JACOB%ENT(1,2)-JETA*JACOB%ENT(1,1)*JACOB%ENT(1,2))/J**3+(SECOND_PD%X(2)*JACOB%ENT(1,2)-SECOND_PD%X(3)*JACOB%ENT(1,1))/J**2
! 	S(2,1) = (JXI*JACOB%ENT(2,1)*JACOB%ENT(2,2)-JETA*JACOB%ENT(2,1)*JACOB%ENT(2,1))/J**3-(SECOND_PD%Y(1)*JACOB%ENT(2,2)-SECOND_PD%Y(2)*JACOB%ENT(2,1))/J**2
! 	S(2,2) = -(JXI*JACOB%ENT(1,1)*JACOB%ENT(2,2)-JETA*JACOB%ENT(1,1)*JACOB%ENT(2,1))/J**3+(SECOND_PD%X(1)*JACOB%ENT(2,2)-SECOND_PD%X(2)*JACOB%ENT(2,1))/J**2
! 	S(2,3) = (JXI*JACOB%ENT(1,1)*JACOB%ENT(1,2)-JETA*JACOB%ENT(1,1)*JACOB%ENT(1,1))/J**3-(SECOND_PD%X(1)*JACOB%ENT(1,2)-SECOND_PD%X(2)*JACOB%ENT(1,1))/J**2
! 	
! 	DBSFUN(1) =  GET_ALL_DIFF_BSPLINES(REF_PT%X,BASIS_KVEC(1),DIFF_ORDER)
! 	DBSFUN(2) =  GET_ALL_DIFF_BSPLINES(REF_PT%Y,BASIS_KVEC(2),DIFF_ORDER)
! 	
! 	
! 	DO K = 0, DIFF_ORDER
! 	DO L = 0, DIFF_ORDER-K
! 		DWSUM(K,L) = 0.0D0
! 		DO J1 = 0, BASIS_KVEC(1)%POLY_ORDER
! 			INDX_X = DBSFUN(1)%INIT + J1
! 			IF (INDX_X>=0) THEN
! 				DO J2 = 0, BASIS_KVEC(2)%POLY_ORDER
! 					INDX_Y = DBSFUN(2)%INIT + J2
! 					IF (INDX_Y>=0) THEN
! 						DWSUM(K,L) = DWSUM(K,L) + DBSFUN(1)%N(J1,K)*DBSFUN(2)%N(J2,L)*BASIS_CTL%WGTS(INDX_X,INDX_Y,0)
! 					ENDIF
! 				ENDDO
! 			ENDIF
! 		ENDDO
! 	ENDDO
! 	ENDDO
! 
! 	LC_INDX = 0
! 	
! 	DO I1 = 0, BASIS_KVEC(1)%POLY_ORDER
! 		
! 		INDX_X = DBSFUN(1)%INIT + I1
! 
! 	DO I2 = 0, BASIS_KVEC(2)%POLY_ORDER
! 		
! 		INDX_Y = DBSFUN(2)%INIT + I2
! 		LC_INDX = LC_INDX + 1
! 		INDX(LC_INDX) = INT2D(INDX_X, INDX_Y)
! 		
! 		DO K = 0, DIFF_ORDER
! 		DO L = 0, DIFF_ORDER-K
! 		
! 			DIFF_NURBS%VAL(K,L) = DBSFUN(1)%N(I1,K)*DBSFUN(2)%N(I2,L)*BASIS_CTL%WGTS(INDX_X,INDX_Y,0)
! 			
! 			DO J1 = 1, K
! 				DIFF_NURBS%VAL(K,L) = DIFF_NURBS%VAL(K,L) - BINOM(K,J1)*DWSUM(J1,0)*DIFF_NURBS%VAL(K-J1,L)
! 			ENDDO
! 			DO J2 = 1, L
! 				DIFF_NURBS%VAL(K,L) = DIFF_NURBS%VAL(K,L) - BINOM(L,J2)*DWSUM(0,J2)*DIFF_NURBS%VAL(K,L-J2)
! 			ENDDO
! 			DO J1 = 1, K
! 			DO J2 = 1, L
! 				DIFF_NURBS%VAL(K,L) = DIFF_NURBS%VAL(K,L) - BINOM(K,J1)*BINOM(L,J2)*DWSUM(J1,J2)*DIFF_NURBS%VAL(K-J1,L-J2)
! 			ENDDO
! 			ENDDO
! 			DIFF_NURBS%VAL(K,L) = DIFF_NURBS%VAL(K,L) / DWSUM(0,0)
! 		ENDDO
! 		ENDDO
! 		
! 		SF(LC_INDX)%D00 = DIFF_NURBS%VAL(0,0)
! 		SF(LC_INDX)%D10 = DIFF_NURBS%VAL(1,0)*INV_JACOB%ENT(1,1) + DIFF_NURBS%VAL(0,1)*INV_JACOB%ENT(2,1)
! 		SF(LC_INDX)%D01 = DIFF_NURBS%VAL(1,0)*INV_JACOB%ENT(1,2) + DIFF_NURBS%VAL(0,1)*INV_JACOB%ENT(2,2)
! 		SF(LC_INDX)%D20 = DIFF_NURBS%VAL(2,0)*INV_JACOB%ENT(1,1)**2 + 2.0D0*DIFF_NURBS%VAL(1,1)*INV_JACOB%ENT(1,1)*INV_JACOB%ENT(2,1) + DIFF_NURBS%VAL(0,2)*INV_JACOB%ENT(2,1)**2 + DIFF_NURBS%VAL(1,0)*S(1,1) + DIFF_NURBS%VAL(0,1)*S(2,1)
! 		SF(LC_INDX)%D11 = DIFF_NURBS%VAL(2,0)*INV_JACOB%ENT(1,1)*INV_JACOB%ENT(1,2) + DIFF_NURBS%VAL(1,1)*(INV_JACOB%ENT(1,1)*INV_JACOB%ENT(2,2)+INV_JACOB%ENT(1,2)*INV_JACOB%ENT(2,1)) + DIFF_NURBS%VAL(0,2)*INV_JACOB%ENT(2,1)*INV_JACOB%ENT(2,2) + DIFF_NURBS%VAL(1,0)*S(1,2) + DIFF_NURBS%VAL(0,1)*S(2,2)
! 		SF(LC_INDX)%D02 = DIFF_NURBS%VAL(2,0)*INV_JACOB%ENT(1,2)**2 + 2.0D0*DIFF_NURBS%VAL(1,1)*INV_JACOB%ENT(1,2)*INV_JACOB%ENT(2,2) + DIFF_NURBS%VAL(0,2)*INV_JACOB%ENT(2,2)**2 + DIFF_NURBS%VAL(1,0)*S(1,3) + DIFF_NURBS%VAL(0,1)*S(2,3)
! 		
! 	ENDDO
! 	ENDDO
! 	
! END SUBROUTINE GET_ALL_PHY_NURBS_SURFACE_2D
! 
! 
! 
! 
! 
! 
! !! FIND ALL NONVANISHING BASIS FUNCTION ON PHYSICAL SPACE
! SUBROUTINE GET_ALL_PHY_BASIS_IN_INT(SF, INDX, REF_PT, JACOB)
! 
! 	TYPE(FVALUE), INTENT(OUT) :: SF((BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1))
! 	TYPE(INT2D), INTENT(OUT) :: INDX((BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1))
! 	TYPE(POINT2D), INTENT(IN) :: REF_PT
! 	TYPE(MATRIX_22), INTENT(IN) :: JACOB
! 	
! 	REAL*8 :: DJ, DJXI, DJETA, STEPFT(3), INV_JXI(2,2), INV_JETA(2,2), INV_J(2,2), DUF(2), DUXF(2), DUYF(2), DUFXI(2), DUFETA(2)
! 	TYPE(SECOND_PARTIAL_DERIVATIVES) :: SECOND_PD
! 	TYPE(DIFF_BSPLINES) :: NX, NY
! 	TYPE(MATRIX_22) :: INV_JACOB
! 	INTEGER :: I, K, II, JJ, KK
! 
! 	REAL*8 :: JXI, JETA, S(2,3)
! 	
! 	INV_JACOB = .INVERSE.JACOB
! 	
! ! 	INV_J(1,1) = INV_JACOB%ENT(1,1)
! ! 	INV_J(1,2) = INV_JACOB%ENT(1,2)
! ! 	INV_J(2,1) = INV_JACOB%ENT(2,1)
! ! 	INV_J(2,2) = INV_JACOB%ENT(2,2)
! 	
! 	SECOND_PD = GET_PARTIAL(REF_PT)				!! P^2(X)/P(XI^2), P^2(X)/P(XI,ETA), P^2(X)/P(ETA^2), P^2(Y)/P(XI^2), P^2(Y)/P(XI,ETA), P^2(Y)/P(ETA^2)
! 
! !  	DJ = JACOB%ENT(1,1)*JACOB%ENT(2,2)-JACOB%ENT(1,2)*JACOB%ENT(2,1)
! ! 	DJXI = SECOND_PD%X(1)*JACOB%ENT(2,2)+JACOB%ENT(1,1)*SECOND_PD%Y(2)-SECOND_PD%y(1)*JACOB%ENT(2,1)-JACOB%ENT(1,2)*SECOND_PD%x(2)
! ! 	DJETA = SECOND_PD%X(2)*JACOB%ENT(2,2)+JACOB%ENT(1,1)*SECOND_PD%Y(3)-SECOND_PD%y(2)*JACOB%ENT(2,1)-JACOB%ENT(1,2)*SECOND_PD%x(3)
! ! 
! ! 	INV_JXI(1,1) =  (SECOND_PD%Y(2)*DJ - JACOB%ENT(2,2)*DJXI)/DJ**2
! ! 	INV_JXI(1,2) = -(SECOND_PD%Y(1)*DJ - JACOB%ENT(1,2)*DJXI)/DJ**2
! ! 	INV_JXI(2,1) = -(SECOND_PD%X(2)*DJ - JACOB%ENT(2,1)*DJXI)/DJ**2
! ! 	INV_JXI(2,2) =  (SECOND_PD%X(1)*DJ - JACOB%ENT(1,1)*DJXI)/DJ**2
! ! 	
! ! 	INV_JETA(1,1) = (SECOND_PD%Y(3)*DJ - JACOB%ENT(2,2)*DJETA)/DJ**2
! ! 	INV_JETA(1,2) = (SECOND_PD%Y(2)*DJ - JACOB%ENT(1,2)*DJETA)/DJ**2
! ! 	INV_JETA(2,1) = (SECOND_PD%X(3)*DJ - JACOB%ENT(2,1)*DJETA)/DJ**2
! ! 	INV_JETA(2,2) = (SECOND_PD%X(2)*DJ - JACOB%ENT(1,1)*DJETA)/DJ**2
! 
!  	DJ = JACOB%ENT(1,1)*JACOB%ENT(2,2)-JACOB%ENT(1,2)*JACOB%ENT(2,1)
! 	JXI = SECOND_PD%X(1)*JACOB%ENT(2,2)+JACOB%ENT(1,1)*SECOND_PD%Y(2)-SECOND_PD%X(2)*JACOB%ENT(2,1)-JACOB%ENT(1,2)*SECOND_PD%Y(1)
! 	JETA = SECOND_PD%X(2)*JACOB%ENT(2,2)+JACOB%ENT(1,1)*SECOND_PD%Y(3)-SECOND_PD%X(3)*JACOB%ENT(2,1)-JACOB%ENT(1,2)*SECOND_PD%Y(2)
! 
! 	S(1,1) = -(JXI*JACOB%ENT(2,2)*JACOB%ENT(2,2)-JETA*JACOB%ENT(2,1)*JACOB%ENT(2,2))/DJ**3+(SECOND_PD%Y(2)*JACOB%ENT(2,2)-SECOND_PD%Y(3)*JACOB%ENT(2,1))/DJ**2
! 	S(1,2) = (JXI*JACOB%ENT(1,2)*JACOB%ENT(2,2)-JETA*JACOB%ENT(1,2)*JACOB%ENT(2,1))/DJ**3-(SECOND_PD%X(2)*JACOB%ENT(2,2)-SECOND_PD%X(3)*JACOB%ENT(2,1))/DJ**2
! 	S(1,3) = -(JXI*JACOB%ENT(1,2)*JACOB%ENT(1,2)-JETA*JACOB%ENT(1,1)*JACOB%ENT(1,2))/DJ**3+(SECOND_PD%X(2)*JACOB%ENT(1,2)-SECOND_PD%X(3)*JACOB%ENT(1,1))/DJ**2
! 	S(2,1) = (JXI*JACOB%ENT(2,1)*JACOB%ENT(2,2)-JETA*JACOB%ENT(2,1)*JACOB%ENT(2,1))/DJ**3-(SECOND_PD%Y(1)*JACOB%ENT(2,2)-SECOND_PD%Y(2)*JACOB%ENT(2,1))/DJ**2
! 	S(2,2) = -(JXI*JACOB%ENT(1,1)*JACOB%ENT(2,2)-JETA*JACOB%ENT(1,1)*JACOB%ENT(2,1))/DJ**3+(SECOND_PD%X(1)*JACOB%ENT(2,2)-SECOND_PD%X(2)*JACOB%ENT(2,1))/DJ**2
! 	S(2,3) = (JXI*JACOB%ENT(1,1)*JACOB%ENT(1,2)-JETA*JACOB%ENT(1,1)*JACOB%ENT(1,1))/DJ**3-(SECOND_PD%X(1)*JACOB%ENT(1,2)-SECOND_PD%X(2)*JACOB%ENT(1,1))/DJ**2
! 
! 	NX = GET_ALL_DIFF_BSPLINES(REF_PT%X, BASIS_KVEC(1), 2)
! 	NY = GET_ALL_DIFF_BSPLINES(REF_PT%Y, BASIS_KVEC(2), 2)
! 	
! ! 	IF (DABS(REF_PT%X-1.0D0)<=EPS) THEN
! ! 		PRINT*, '---------NX-16TH----------'
! ! 		PRINT*, NX%N(7,:)
! ! 		PRINT*, '---------NX-17TH----------'
! ! 		PRINT*, NX%N(8,:)
! ! 		STOP
! ! 	ENDIF
! 
! ! 	IF (DABS(REF_PT%Y-1.0D0)<=EPS) THEN
! ! 		PRINT*, '---------NY-3TH----------'
! ! 		PRINT*, NY%N(2,:)
! ! 		PRINT*, '---------NY-4TH----------'
! ! 		PRINT*, NY%N(3,:)
! ! 		STOP
! ! 	ENDIF
! 
! 	K = 0
! 	DO J=0, NY%POLY_ORDER
! 		DO I=0, NX%POLY_ORDER
! 			K = K + 1
! 			INDX(K) = INT2D(NX%INIT+I, NY%INIT+J)
! 			
! ! 			DUF = MATMUL(INV_J, (/NX%N(I,1)*NY%N(J,0), NX%N(I,0)*NY%N(J,1)/))
! ! 			
! ! 			DUFXI(1) = (INV_JXI(1,1)*NX%N(I,1)*NY%N(J,0) + INV_J(1,1)*NX%N(I,2)*NY%N(J,0)) + (INV_JXI(1,2)*NX%N(I,0)*NY%N(J,1) + INV_J(1,2)*NX%N(I,1)*NY%N(J,1))
! ! 			DUFXI(2) = (INV_JETA(1,1)*NX%N(I,1)*NY%N(J,0) + INV_J(1,1)*NX%N(I,1)*NY%N(J,1)) + (INV_JETA(1,2)*NX%N(I,0)*NY%N(J,1) + INV_J(1,2)*NX%N(I,0)*NY%N(J,2))
! ! 			
! ! 			DUFETA(1) = (INV_JXI(2,1)*NX%N(I,1)*NY%N(J,0) + INV_J(2,1)*NX%N(I,2)*NY%N(J,0)) + (INV_JXI(2,2)*NX%N(I,0)*NY%N(J,1) + INV_J(2,2)*NX%N(I,1)*NY%N(J,1))
! ! 			DUFETA(2) = (INV_JETA(2,1)*NX%N(I,1)*NY%N(J,0) + INV_J(2,1)*NX%N(I,1)*NY%N(J,1)) + (INV_JETA(2,2)*NX%N(I,0)*NY%N(J,1) + INV_J(2,2)*NX%N(I,0)*NY%N(J,2))
! ! 			
! ! 			DUXF = MATMUL(INV_J, DUFXI)
! ! 			DUYF = MATMUL(INV_J, DUFETA)
! ! 			
! ! 			SF(K)%D00 = NX%N(I,0)*NY%N(J,0)
! ! 			SF(K)%D10 = DUF(1)
! ! 			SF(K)%D01 = DUF(2)
! ! 			SF(K)%D20 = DUXF(1)
! ! 			SF(K)%D11 = DUXF(2)
! ! 			SF(K)%D02 = DUYF(2)
! 			
! 			SF(K)%D00 = NX%N(I,0)*NY%N(J,0)
! 			SF(K)%D10 = NX%N(I,1)*NY%N(J,0)*INV_JACOB%ENT(1,1) + NX%N(I,0)*NY%N(J,1)*INV_JACOB%ENT(2,1)
! 			SF(K)%D01 = NX%N(I,1)*NY%N(J,0)*INV_JACOB%ENT(1,2) + NX%N(I,0)*NY%N(J,1)*INV_JACOB%ENT(2,2)
! 			SF(K)%D20 = NX%N(I,2)*NY%N(J,0)*INV_JACOB%ENT(1,1)**2 + 2.0D0*NX%N(I,1)*NY%N(J,1)*INV_JACOB%ENT(1,1)*INV_JACOB%ENT(2,1) + NX%N(I,0)*NY%N(J,2)*INV_JACOB%ENT(2,1)**2 + NX%N(I,1)*NY%N(J,0)*S(1,1) + NX%N(I,0)*NY%N(J,1)*S(2,1)
! 			SF(K)%D11 = NX%N(I,2)*NY%N(J,0)*INV_JACOB%ENT(1,1)*INV_JACOB%ENT(1,2) + NX%N(I,1)*NY%N(J,1)*(INV_JACOB%ENT(1,1)*INV_JACOB%ENT(2,2)+INV_JACOB%ENT(1,2)*INV_JACOB%ENT(2,1)) + NX%N(I,0)*NY%N(J,2)*INV_JACOB%ENT(2,1)*INV_JACOB%ENT(2,2) + NX%N(I,1)*NY%N(J,0)*S(1,2) + NX%N(I,0)*NY%N(J,1)*S(2,2)
! 			SF(K)%D02 = NX%N(I,2)*NY%N(J,0)*INV_JACOB%ENT(1,2)**2 + 2.0D0*NX%N(I,1)*NY%N(J,1)*INV_JACOB%ENT(1,2)*INV_JACOB%ENT(2,2) + NX%N(I,0)*NY%N(J,2)*INV_JACOB%ENT(2,2)**2 + NX%N(I,1)*NY%N(J,0)*S(1,3) + NX%N(I,0)*NY%N(J,1)*S(2,3)
! 
! 		ENDDO
! 	ENDDO
! ! 	PRINT*, INDX(1),SF(1)
! ! 	STOP
! END SUBROUTINE GET_ALL_PHY_BASIS_IN_INT
! 
! 
! 
! 
! 
! 
! TYPE(FVALUE) FUNCTION GET_PHY_NURBS_SURFACE_2D(REF_PT, IX, IY, JACOB)
! 
! 	INTEGER, INTENT(IN) :: IX, IY
! 	TYPE(POINT2D), INTENT(IN) :: REF_PT
! 	TYPE(MATRIX_22), INTENT(IN) :: JACOB
! 
! 	TYPE(MATRIX_22) :: INV_JACOB
! 	TYPE(FUNCTION_2D) :: REF_SF, DIFF_NURBS
! 	TYPE(DIFF_BSPLINES) :: DBSFUN(2)
! 	REAL(8) :: DWSUM(0:MAX_DIFF_ORDER,0:MAX_DIFF_ORDER)
! 	INTEGER :: INDX_X, INDX_Y, DIFF_ORDER
! 	INTEGER :: I, J, K, L, J1, J2, I1, I2, LC_INDX
! 
! 	DIFF_ORDER = 1
! 
! 	INV_JACOB = .INVERSE.JACOB
! 	
! 	DBSFUN(1) =  GET_ALL_DIFF_BSPLINES(REF_PT%X,BASIS_KVEC(1),DIFF_ORDER)
! 	DBSFUN(2) =  GET_ALL_DIFF_BSPLINES(REF_PT%Y,BASIS_KVEC(2),DIFF_ORDER)
! 
! 	DO K = 0, DIFF_ORDER
! 	DO L = 0, DIFF_ORDER-K
! 		DWSUM(K,L) = 0.0D0
! 		DO J1 = 0, BASIS_KVEC(1)%POLY_ORDER
! 			INDX_X = DBSFUN(1)%INIT + J1
! 			IF (INDX_X>=0) THEN
! 				DO J2 = 0, BASIS_KVEC(2)%POLY_ORDER
! 					INDX_Y = DBSFUN(2)%INIT + J2
! 					IF (INDX_Y>=0) THEN
! 						DWSUM(K,L) = DWSUM(K,L) + DBSFUN(1)%N(J1,K)*DBSFUN(2)%N(J2,L)*BASIS_CTL%WGTS(INDX_X,INDX_Y,0)
! 					ENDIF
! 				ENDDO
! 			ENDIF
! 		ENDDO
! 	ENDDO
! 	ENDDO
! 
! 	REF_SF = GET_BASIS(REF_PT,(/IX,IY/))
! 		
! 	DO K = 0, DIFF_ORDER
! 	DO L = 0, DIFF_ORDER-K
! 	
! 		DIFF_NURBS%VAL(K,L) = REF_SF%VAL(K,L)*BASIS_CTL%WGTS(IX,IY,0)
! 		
! 		DO J1 = 1, K
! 			DIFF_NURBS%VAL(K,L) = DIFF_NURBS%VAL(K,L) - BINOM(K,J1)*DWSUM(J1,0)*DIFF_NURBS%VAL(K-J1,L)
! 		ENDDO
! 		DO J2 = 1, L
! 			DIFF_NURBS%VAL(K,L) = DIFF_NURBS%VAL(K,L) - BINOM(L,J2)*DWSUM(0,J2)*DIFF_NURBS%VAL(K,L-J2)
! 		ENDDO
! 		DO J1 = 1, K
! 		DO J2 = 1, L
! 			DIFF_NURBS%VAL(K,L) = DIFF_NURBS%VAL(K,L) - BINOM(K,J1)*BINOM(L,J2)*DWSUM(J1,J2)*DIFF_NURBS%VAL(K-J1,L-J2)
! 		ENDDO
! 		ENDDO
! 
! 		DIFF_NURBS%VAL(K,L) = DIFF_NURBS%VAL(K,L) / DWSUM(0,0)
! 
! 	ENDDO
! 	ENDDO
! 	
! 	GET_PHY_NURBS_SURFACE_2D%D00 = DIFF_NURBS%VAL(0,0)
! 	GET_PHY_NURBS_SURFACE_2D%D10 = DIFF_NURBS%VAL(1,0)*INV_JACOB%ENT(1,1) + DIFF_NURBS%VAL(0,1)*INV_JACOB%ENT(2,1)
! 	GET_PHY_NURBS_SURFACE_2D%D01 = DIFF_NURBS%VAL(1,0)*INV_JACOB%ENT(1,2) + DIFF_NURBS%VAL(0,1)*INV_JACOB%ENT(2,2)
! 		
! END FUNCTION GET_PHY_NURBS_SURFACE_2D
! 
! !!  FIND BASIS FUNCTION ON PARAMETRIC SPACE
! TYPE(FUNCTION_2D) FUNCTION GET_BASIS(REF_PT,INDX)
! 
! 	TYPE(POINT2D), INTENT(IN) :: REF_PT
! 	INTEGER, INTENT(IN) :: INDX(2)
! 
! 	TYPE(FUNCTION_1D) :: NX, NY
! 
! 	NX = GET_DIFF_BSPLINE(REF_PT%X,BASIS_KVEC(1),INDX(1),2)
! 	NY = GET_DIFF_BSPLINE(REF_PT%Y,BASIS_KVEC(2),INDX(2),2)
! 
! 	GET_BASIS%VAL(0,0) = NX%VAL(0) * NY%VAL(0)
! 	GET_BASIS%VAL(1,0) = NX%VAL(1) * NY%VAL(0)
! 	GET_BASIS%VAL(0,1) = NX%VAL(0) * NY%VAL(1)
! 	GET_BASIS%VAL(2,0) = NX%VAL(2) * NY%VAL(0)
! 	GET_BASIS%VAL(1,1) = NX%VAL(1) * NY%VAL(1)
! 	GET_BASIS%VAL(0,2) = NX%VAL(0) * NY%VAL(2)
! 
! END FUNCTION GET_BASIS

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

! NURBS PU WITH FLAT-TOP

TYPE(FUNCTION_1D) FUNCTION GET_BSPLINEPU1D(PHYX, PATCH)

	REAL*8, INTENT(IN) :: PHYX
	INTEGER, INTENT(IN) :: PATCH
	
	TYPE(FUNCTION_1D) :: NX, REFX
	INTEGER :: I, J, K
	
	REFX%VAL(0) = PHYX
	
	GET_BSPLINEPU1D%VAL(:) = 0.0D0
	
	DO I = 0, 2*PU_KVEC%POLY_ORDER - 3
		NX = GET_DIFF_BSPLINE(REFX%VAL(0), PU_KVEC, I + (PATCH-1)*(2*PU_KVEC%POLY_ORDER - 2), 2)
		GET_BSPLINEPU1D = GET_BSPLINEPU1D + NX
		NX%VAL(:) = 0.0D0
	ENDDO
	
! 	IF (DABS(REFX%VAL(0) - COL_PT(4))<=EPS) THEN
! 		PRINT*, GET_BSPLINEPU1D%VAL(:)
! 	ENDIF
	
END FUNCTION GET_BSPLINEPU1D


TYPE(FUNCTION_1D) FUNCTION GET_PHYPU1D(PARPT, PATCH) ! PARPT is a point in the parameter space.

	REAL*8, INTENT(IN) :: PARPT
	INTEGER, INTENT(IN) :: PATCH
	
	TYPE(FUNCTION_1D) :: PHYPT, REFPT, PHYPU

! 	IF (PATCH==1 .AND. PARPT>PATCHBDPT(1,2) + DELTA) THEN 
! 		GOTO 78
! 	ELSEIF (PATCH==2 .AND. PARPT<PATCHBDPT(2,1) - DELTA) THEN 
! 		GOTO 78
! 	ENDIF
	
	IF (PATCH==1) THEN 
		PHYPT = MAP_F(PARPT)
	ELSEIF (PATCH==2) THEN
		PHYPT = MAP_G(PARPT)
	ENDIF
	
	REFPT = PATCH_TO_REFPU(PHYPT%VAL(0), PATCH)
	
	PHYPU%VAL(0) = PU1D(REFPT%VAL(0), 0)
	PHYPU%VAL(1) = PU1D(REFPT%VAL(0), 1)*REFPT%VAL(1)
	PHYPU%VAL(2) = PU1D(REFPT%VAL(0), 2)*(REFPT%VAL(1))**2 + PU1D(REFPT%VAL(0), 1)*REFPT%VAL(2)
	
	GET_PHYPU1D%VAL(0) = PHYPU%VAL(0)
	GET_PHYPU1D%VAL(1) = PHYPU%VAL(1)*PHYPT%VAL(1)
	GET_PHYPU1D%VAL(2) = PHYPU%VAL(2)*(PHYPT%VAL(1))**2 + PHYPU%VAL(1)*PHYPT%VAL(2)

! 	GOTO 79
! 	
! 	78 CONTINUE
! 	
! 	GET_PHYPU1D%VAL(:) = 0.0D0
! 	
! 	79 CONTINUE

END FUNCTION GET_PHYPU1D


! TYPE(FUNCTION_1D) FUNCTION GET_PHYPU1D(PARPT, PATCH) ! PARPT is a point in the parameter space.
! 
! 	REAL*8, INTENT(IN) :: PARPT
! 	INTEGER, INTENT(IN) :: PATCH
! 	
! 	TYPE(FUNCTION_1D) :: PHYPT, REFPT, PHYPU
! 	
! 	IF (PATCH==1) THEN 
! 		PHYPT = MAP_F(PARPT, 5.0D0)
! 	ELSEIF (PATCH==2) THEN
! 		PHYPT = MAP_G(PARPT)
! 	ENDIF
! 	
! 	IF (PATCH==1 .AND. PARPT>PATCHBDPT(1,2) + DELTA) THEN 
! 		GOTO 78
! 	ELSEIF (PATCH==2 .AND. PARPT<PATCHBDPT(2,1) - DELTA) THEN 
! 		GOTO 78
! 	ENDIF
! 	
! 	REFPT = PATCH_TO_REFPU(PHYPT%VAL(0), PATCH)
! 	
! 	PHYPU%VAL(0) = PU1D(REFPT%VAL(0), 0)
! 	PHYPU%VAL(1) = PU1D(REFPT%VAL(0), 1)*REFPT%VAL(1)
! 	PHYPU%VAL(2) = PU1D(REFPT%VAL(0), 2)*(REFPT%VAL(1))**2 + PU1D(REFPT%VAL(0), 1)*REFPT%VAL(2)
! 	
! 	GET_PHYPU1D%VAL(0) = PHYPU%VAL(0)
! 	GET_PHYPU1D%VAL(1) = PHYPU%VAL(1)*PHYPT%VAL(1)
! 	GET_PHYPU1D%VAL(2) = PHYPU%VAL(2)*(PHYPT%VAL(1))**2 + PHYPU%VAL(1)*PHYPT%VAL(2)
! 	
! 	GOTO 79
! 	
! 	78 CONTINUE
! 	
! 	GET_PHYPU1D%VAL(:) = 0.0D0
! 	
! 	79 CONTINUE
! 	
! END FUNCTION GET_PHYPU1D


! TYPE(FUNCTION_1D) FUNCTION GET_PHYPU1D(PARPT, PATCH) ! PARPT is a point in the parameter space.
! 
! 	REAL*8, INTENT(IN) :: PARPT
! 	INTEGER, INTENT(IN) :: PATCH
! 	
! 	TYPE(FUNCTION_1D) :: PHYPT, REFPT, PHYPU
! 	
! ! 	IF (PATCH==1) THEN 
! ! 		PHYPT = MAP_F(PARPT, 5.0D0)
! ! 	ELSEIF (PATCH==2) THEN
! ! 		PHYPT = MAP_G(PARPT)
! ! 	ENDIF
! 	
! 	IF (PATCH==1 .AND. PARPT>PATCHBDPT(1,2) + DELTA) THEN 
! 		GOTO 78
! 	ELSEIF (PATCH==2 .AND. PARPT<PATCHBDPT(2,1) - DELTA) THEN 
! 		GOTO 78
! 	ENDIF
! 	
! 	REFPT = PATCH_TO_REFPU(PARPT, PATCH)
! 	
! 	GET_PHYPU1D%VAL(0) = PU1D(REFPT%VAL(0), 0)
! 	GET_PHYPU1D%VAL(1) = PU1D(REFPT%VAL(0), 1)*REFPT%VAL(1)
! 	GET_PHYPU1D%VAL(2) = PU1D(REFPT%VAL(0), 2)*(REFPT%VAL(1))**2 + PU1D(REFPT%VAL(0), 1)*REFPT%VAL(2)
! 	
! 	GOTO 79
! 	
! 	78 CONTINUE
! 	
! 	GET_PHYPU1D%VAL(:) = 0.0D0
! 	
! 	79 CONTINUE
! 	
! END FUNCTION GET_PHYPU1D


REAL*8 FUNCTION PU1D(X, FLAGX)

	REAL*8, INTENT(IN) :: X
	INTEGER, INTENT(IN) :: FLAGX

	IF (FLAGX.EQ. 0) THEN													! PU-FUNCTION
		IF ((X + 1.0D0 .GE. EPS) .AND. (X .LT. EPS)) THEN
			IF (PUORDER.EQ.1) THEN
				PU1D=(1.0D0+X)
			ELSEIF (PUORDER.EQ.2) THEN
				PU1D=((1.0D0+X)**2)*(1.0D0-2.0D0*X)
			ELSEIF (PUORDER.EQ.3) THEN
				PU1D=((1.0D0+X)**3)*(1.0D0-3.0D0*X+6.0D0*X**2)
			ELSEIF (PUORDER.EQ.4) THEN
				PU1D=((1.0D0+X)**4)*(1.0D0-4.0D0*X+10.0D0*X**2-20.0D0*X**3)
			ELSEIF (PUORDER.EQ.5) THEN
				PU1D=((1.0D0+X)**5)*(1.0D0-5.0D0*X+15.0D0*X**2-35.0D0*X**3+70.0D0*X**4)
			ELSEIF (PUORDER.EQ.6) THEN
				PU1D=((1.0D0+X)**6.0D0)*(1.0D0-6.0D0*X+21.0D0*X**2.0D0-56.0D0*X**3.0D0+126.0D0*X**4.0D0 &
				-252.0D0*X**5.0D0)
			ELSEIF (PUORDER.EQ.7) THEN
				PU1D=((1.0D0+X)**7)*(1.0D0-7.0D0*X+28.0D0*X**2-84.0D0*X**3+210.0D0*X**4-462.0D0*X**5 &
				+924.0D0*X**6)
			ENDIF
		ELSEIF ((X .GE. EPS) .AND. (X - 1.0D0 .LT. EPS)) THEN
			IF (PUORDER.EQ.1) THEN
				PU1D=(1.0D0-X)
			ELSEIF (PUORDER.EQ.2) THEN
				PU1D=((1.0D0-X)**2)*(1.0D0+2.0D0*X)
			ELSEIF (PUORDER.EQ.3) THEN
				PU1D=((1.0D0-X)**3)*(1.0D0+3.0D0*X+6.0D0*X**2)
			ELSEIF (PUORDER.EQ.4) THEN
				PU1D=((1.0D0-X)**4)*(1.0D0+4.0D0*X+10.0D0*X**2+20.0D0*X**3)
			ELSEIF (PUORDER.EQ.5) THEN
				PU1D=((1.0D0-X)**5)*(1.0D0+5.0D0*X+15.0D0*X**2.0D0+35.0D0*X**3.0D0+70.0D0*X**4)
			ELSEIF (PUORDER.EQ.6) THEN
				PU1D=((1.0D0-X)**6)*(1.0D0+6.0D0*X+21.0D0*X**2+56.0D0*X**3+126.0D0*X**4+252.0D0*X**5)
			ELSEIF (PUORDER.EQ.7) THEN
				PU1D=((1.0D0-X)**7)*(1.0D0+7.0D0*X+28.0D0*X**2+84.0D0*X**3+210.0D0*X**4+462.0D0*X**5 &
				+924.0D0*X**6)
			ENDIF
		ELSE
			PU1D=0.0D0
		ENDIF
	ELSEIF (FLAGX.EQ.1) THEN												! DIFFERENTIATION OF PU-FUNCTION
		IF ((X + 1.0D0 .GE. EPS) .AND. (X .LT. EPS)) THEN
			IF (PUORDER.EQ.1) THEN
				PU1D=1.0D0
			ELSEIF (PUORDER.EQ.2) THEN
				PU1D=-6.0D0*X*(1.0D0 + X)
			ELSEIF (PUORDER.EQ.3) THEN
				PU1D=30.0D0*X**2*(1.0D0 + X)**2
			ELSEIF (PUORDER.EQ.4) THEN
				PU1D=-140.0D0*X**3*(1.0D0 + X)**3
			ELSEIF (PUORDER.EQ.5) THEN
				PU1D=630.0D0*X**4*(1.0D0 + X)**4
			ELSEIF (PUORDER.EQ.6) THEN
				PU1D=-2772.0D0*X**5*(1.0D0 + X)**5
			ELSEIF (PUORDER.EQ.7) THEN
				PU1D=12012.0D0*X**6*(1.0D0 + X)**6
			ENDIF
		ELSEIF ((X .GT. EPS) .AND. (X - 1.0D0 .LE. EPS)) THEN
			IF (PUORDER.EQ.1) THEN
				PU1D=-1.0D0
			ELSEIF (PUORDER.EQ.2) THEN
				PU1D=6.0D0*(-1.0D0 + X)*X
			ELSEIF (PUORDER.EQ.3) THEN
				PU1D=-30.0D0*(-1.0D0 + X)**2*X**2
			ELSEIF (PUORDER.EQ.4) THEN
				PU1D=140.0D0*(-1.0D0 + X)**3*X**3
			ELSEIF (PUORDER.EQ.5) THEN
				PU1D=-630.0D0*(-1.0D0 + X)**4*X**4
			ELSEIF (PUORDER.EQ.6) THEN
				PU1D=2772.0D0*(-1.0D0 + X)**5*X**5
			ELSEIF (PUORDER.EQ.7) THEN
				PU1D=-12012.0D0*(-1.0D0 + X)**6*X**6
			ENDIF
        ELSE
            PU1D=0.0D0
		ENDIF
	ELSEIF (FLAGX.EQ.2) THEN												! DIFFERENTIATION OF PU-FUNCTION
		IF ((X + 1.0D0 .GE. EPS) .AND. (X .LT. EPS)) THEN
			IF (PUORDER.EQ.1) THEN
				PU1D=0.0D0
			ELSEIF (PUORDER.EQ.2) THEN
				PU1D=-6*x - 6*(1.0D0 + x)
			ELSEIF (PUORDER.EQ.3) THEN
				PU1D=60*x**2*(1.0D0 + X) + 60*x*(1.0D0 + X)**2
			ELSEIF (PUORDER.EQ.4) THEN
				PU1D=-420*x**3*(1.0D0 + X)**2 - 420*x**2*(1.0D0 + X)**3
			ELSEIF (PUORDER.EQ.5) THEN
				PU1D=2520*x**4*(1.0D0 + X)**3 + 2520*x**3*(1.0D0 + X)**4
			ELSEIF (PUORDER.EQ.6) THEN
				PU1D=-13860*x**5*(1.0D0 + X)**4 - 13860*x**4*(1.0D0 + X)**5
			ELSEIF (PUORDER.EQ.7) THEN
				PU1D=72072*x**6*(1.0D0 + X)**5 + 72072*x**5*(1.0D0 + X)**6
			ENDIF
		ELSEIF ((X .GT. EPS) .AND. (X - 1.0D0 .LE. EPS)) THEN
			IF (PUORDER.EQ.1) THEN
				PU1D=0.0D0
			ELSEIF (PUORDER.EQ.2) THEN
				PU1D=6*x + 6*(-1.0D0 + X)
			ELSEIF (PUORDER.EQ.3) THEN
				PU1D=-60*x**2*(-1.0D0 + X) - 60*x*(-1.0D0 + X)**2
			ELSEIF (PUORDER.EQ.4) THEN
				PU1D=420*x**3*(-1.0D0 + X)**2 + 420*x**2*(-1.0D0 + X)**3
			ELSEIF (PUORDER.EQ.5) THEN
				PU1D=-2520*x**4*(-1.0D0 + X)**3 - 2520*x**3*(-1.0D0 + X)**4
			ELSEIF (PUORDER.EQ.6) THEN
				PU1D=13860*x**5*(-1.0D0 + X)**4 + 13860*x**4*(-1.0D0 + X)**5
			ELSEIF (PUORDER.EQ.7) THEN
				PU1D=-72072*x**6*(-1.0D0 + X)**5 - 72072*x**5*(-1.0D0 + X)**6
			ENDIF
        ELSE
            PU1D=0.0D0
		ENDIF
		IF (DABS(X).LE.EPS) THEN
            PU1D=0.0D0
        ENDIF
	ENDIF
END FUNCTION PU1D

END MODULE NURBS_PU