MODULE ERRORESTIMATE

	USE GEOMETRY
	USE NURBS_BASIS
	USE LOADFUNCTION
	USE GSQUAD

    IMPLICIT NONE
    
CONTAINS

!----MAX. NORM ESTIMATE----
SUBROUTINE MAXNORM(MAX_NORM, COEFF_SOL)

	REAL*8, INTENT(OUT) :: MAX_NORM(5)
	REAL*8, INTENT(IN) :: COEFF_SOL(2*DOF)
	TYPE(POINT2D) :: PHY_PT, REF_PT
	INTEGER :: II, I, J
	TYPE(POINT2D) :: EXDISP, APDISP, ERR_DISP, ERR_LINE_DISP, ERR_POLAR_DISP, TMP_ERR_DISP, MAXDISP
	TYPE(STRESS) :: EXSTR, APSTR, ERR_STR, TMP_ERR_STR, ERR_LINE_STR, ERR_POLAR_STR, MAXSTR
	REAL*8 :: R, THETA
	INTEGER :: PATCH
	
	ERR_STR = STRESS(0.D0,0.D0,0.D0,0.D0,0.D0)
	MAXSTR 	= STRESS(0.D0,0.D0,0.D0,0.D0,0.D0)
	
	ERR_DISP = POINT2D(0.D0,0.D0)
	MAXDISP = POINT2D(0.D0,0.D0)

	OPEN(11, FILE = './data/ext_disp')
	OPEN(21, FILE = './data/app_disp')
	OPEN(31, FILE = './data/err_disp')
	OPEN(41, FILE = './data/ext_str')
	OPEN(51, FILE = './data/app_str')
	OPEN(61, FILE = './data/err_str')
	DO PATCH = 1, NUM_PATCH
		DO J = 2, 100
			DO I = 2, 100
				REF_PT = POINT2D((1.D0*(I-1))/100.D0, (1.D0*(J-1))/100.D0)
				PHY_PT = GET_PHY_PT(REF_PT, PATCH)
				IF (DABS(PHY_PT%X).LE.EPS .AND. DABS(PHY_PT%Y).LE.EPS) THEN
					EXDISP = POINT2D(0.D0,0.D0)
					APDISP = POINT2D(0.D0,0.D0)
				ELSE
					CALL GET_RTHETA(R, THETA, PHY_PT)
					CALL APPROXSOL(APDISP, APSTR, REF_PT, COEFF_SOL, PATCH)
					EXDISP = EX_DISP(REF_PT, PATCH)
					EXSTR = EX_STRESS(REF_PT, PATCH)
				ENDIF
				TMP_ERR_DISP%X = DABS(EXDISP%X - APDISP%X)
				TMP_ERR_DISP%Y = DABS(APDISP%Y - EXDISP%Y)
				
				TMP_ERR_STR%SXX = DABS(APSTR%SXX - EXSTR%SXX)
				TMP_ERR_STR%SYY = DABS(APSTR%SYY - EXSTR%SYY)
				TMP_ERR_STR%SXY = DABS(APSTR%SXY - EXSTR%SXY)

				WRITE(11,*) PHY_PT, EXDISP%X, EXDISP%Y
				WRITE(21,*) PHY_PT, APDISP%X, APDISP%Y
				WRITE(31,*) PHY_PT, TMP_ERR_DISP%X, TMP_ERR_DISP%Y
				WRITE(41,*) PHY_PT, EXSTR%SXX, EXSTR%SYY, EXSTR%SXY
				WRITE(51,*) PHY_PT, APSTR%SXX, APSTR%SYY, APSTR%SXY
				WRITE(61,*) PHY_PT, TMP_ERR_STR%SXX, TMP_ERR_STR%SYY, TMP_ERR_STR%SXY
				
				IF (TMP_ERR_DISP%X.GE.ERR_DISP%X) THEN
					ERR_DISP%X = TMP_ERR_DISP%X
				ENDIF
				IF (TMP_ERR_DISP%Y.GE.ERR_DISP%Y) THEN
					ERR_DISP%Y = TMP_ERR_DISP%Y
				ENDIF
				
				IF (TMP_ERR_STR%SXX.GE.ERR_STR%SXX) THEN
					ERR_STR%SXX = TMP_ERR_STR%SXX
				ENDIF
				IF (TMP_ERR_STR%SYY.GE.ERR_STR%SYY) THEN
					ERR_STR%SYY = TMP_ERR_STR%SYY
				ENDIF
				IF (TMP_ERR_STR%SXY.GE.ERR_STR%SXY) THEN
					ERR_STR%SXY = TMP_ERR_STR%SXY
				ENDIF
				IF (DABS(EXDISP%X).GE.MAXDISP%X) THEN
					MAXDISP%X = DABS(EXDISP%X)
				ENDIF
				IF (DABS(EXDISP%Y).GE.MAXDISP%Y) THEN
					MAXDISP%Y = DABS(EXDISP%Y)
				ENDIF
				IF (DABS(EXSTR%SXX).GE.MAXSTR%SXX) THEN
					MAXSTR%SXX = DABS(EXSTR%SXX)
				ENDIF
				IF (DABS(EXSTR%SYY).GE.MAXSTR%SYY) THEN
					MAXSTR%SYY = DABS(EXSTR%SYY)
				ENDIF
				IF (DABS(EXSTR%SXY).GE.MAXSTR%SXY) THEN
					MAXSTR%SXY = DABS(EXSTR%SXY)
				ENDIF
			ENDDO
			WRITE(11,*) ""; WRITE(41,*) ""
			WRITE(21,*) ""; WRITE(51,*) ""
			WRITE(31,*) ""; WRITE(61,*) ""
		ENDDO
		WRITE(11,*) ""; WRITE(41,*) ""
		WRITE(21,*) ""; WRITE(51,*) ""
		WRITE(31,*) ""; WRITE(61,*) ""
	ENDDO
	CLOSE(11); CLOSE(41)
	CLOSE(21); CLOSE(51)
	CLOSE(31); CLOSE(61)
	
	IF (PROBLEM.EQ.8) THEN
		MAX_NORM(1) = 0.D0
		MAX_NORM(2) = 0.D0
		MAX_NORM(3) = ERR_STR%SXX*100.D0/MAXSTR%SXX
		MAX_NORM(4) = ERR_STR%SYY*100.D0/MAXSTR%SYY
		MAX_NORM(5) = ERR_STR%SXY*100.D0/MAXSTR%SXY
	ELSE
		MAX_NORM(1) = ERR_DISP%X*100.D0/MAXDISP%X
		MAX_NORM(2) = ERR_DISP%Y*100.D0/MAXDISP%Y
		MAX_NORM(3) = ERR_STR%SXX*100.D0/MAXSTR%SXX
		MAX_NORM(4) = ERR_STR%SYY*100.D0/MAXSTR%SYY
! 		MAX_NORM(5) = ERR_STR%SXY*100.D0/MAXSTR%SXY
		MAX_NORM(5) = ERR_STR%SXY*100.D0
	ENDIF

	
END SUBROUTINE MAXNORM

SUBROUTINE ENRGY(ENRG, DMY_K, SOL)

	REAL*8, INTENT(IN) :: DMY_K(2*DOF,2*DOF), SOL(2*DOF)
	REAL*8, INTENT(OUT) :: ENRG(4)
	REAL*8 :: AP, TR
	INTEGER :: I, J

	AP = 0.50D0*DOT_PRODUCT(SOL, MATMUL(DMY_K, SOL))

	IF (PROBLEM.EQ.0) THEN
		TR = 0.5d0*(STRESS_E(1,1) + STRESS_E(1,2) + STRESS_E(2,1) + STRESS_E(2,2))
	ELSEIF (PROBLEM.EQ.1) THEN
		TR = 5860.810d0
	ELSEIF (PROBLEM.EQ.2) THEN
		TR = 1253.66300366300360d0
	ELSEIF (PROBLEM.EQ.3) THEN
		TR = 1942.162815444883D0
	ELSEIF (PROBLEM.EQ.4) THEN
		!! Lambda = 2/3
! 		TR = 0.0106234974159766D0
		!! Lambda = 0.544483737
		TR = 4.154544230D0*(1.D0/E)
	ELSEIF (PROBLEM==5) THEN
		!! Polygonal L-shaped
		TR = 4226.229869155190D0
		!! Circular L-shaped
! 		TR = 2758.962779114113d0 
	ENDIF

! 	CALL EXT_ENERGY(TR)

	ENRG(3) = DSQRT(DABS(AP - TR))*100.D0
	ENRG(4) = DSQRT(DABS(AP - TR) / TR)*100.D0

	ENRG(1) = TR; ENRG(2) = AP

!   OPEN(13, FILE=filename, STATUS='unknown', POSITION='append')
! 	WRITE(13,*) ''
! 	WRITE(13,*) 'EXACT ENERGY : ', ENRG(1)
! 	WRITE(13,*) 'APPR. ENERGY : ', ENRG(2)
! 	WRITE(13,*) 'ABS.  ENERGY NORM ERROR (%) : ', ENRG(3)
! 	WRITE(13,*) 'REL.  ENERGY NORM ERROR (%) : ', ENRG(4)
! 	CLOSE(13)
! 

	WRITE(*,*) ""
	WRITE(*,*) 'APPR. ENERGY : ', AP
	PRINT*, ""
	PRINT*, 'REL.  ENERGY NORM ERROR (%) : ', ENRG(4)
	PRINT*, ""


END SUBROUTINE ENRGY

SUBROUTINE L2_NORM_ERROR(L2_NORM, COEFF_SOL)
	
	REAL*8, INTENT(OUT) :: L2_NORM(2)
	REAL*8, INTENT(IN) :: COEFF_SOL(2*DOF)
	INTEGER :: I, J, II, JJ, SUB_NUMLN(2), N, KK, K, PATCH
	REAL*8 :: SUB_LN_LENGTH(2), WEIGHT, DIFF_NN, DET_M
	TYPE(VEC2D) :: SUB_LN
	TYPE(POINT2D) :: GSPT, DMY_GSPT, PHY_PT
	TYPE(MATRIX_22) :: JACOB
	TYPE(POINT2D) :: EXDISP, APDISP, INTF(2)
	TYPE(STRESS) :: APSTR
	
	N = NUMGSPT
	SUB_NUMLN = (/2,2/)
	INTF(:) = POINT2D(0.D0,0.D0)
	
	DO PATCH = 1, NUM_PATCH
		DO JJ = 1, NUMIR(PATCH,1)-1
			SUB_LN_LENGTH(1) = DABS(IR_GRID(PATCH,1,JJ+1) - IR_GRID(PATCH,1,JJ))/(1.D0*SUB_NUMLN(1))
			DO J=1, SUB_NUMLN(1)
				CALL GAULEG(IR_GRID(PATCH,1,JJ)+(J-1)*SUB_LN_LENGTH(1), IR_GRID(PATCH,1,JJ)+J*SUB_LN_LENGTH(1), GSX, GSXW, N)
				DO II = 1, NUMIR(PATCH,2)-1
					SUB_LN_LENGTH(2) = DABS(IR_GRID(PATCH,2,II+1) - IR_GRID(PATCH,2,II))/(1.D0*SUB_NUMLN(2))
					DO I = 1, SUB_NUMLN(2)
						CALL GAULEG(IR_GRID(PATCH,2,II)+(I-1)*SUB_LN_LENGTH(2), IR_GRID(PATCH,2,II)+I*SUB_LN_LENGTH(2), GSY, GSYW, N)
						DO KK = 1, N
							DO K = 1, N
								GSPT = POINT2D(GSX(KK),GSY(K))
								DMY_GSPT = GSPT
								JACOB= GET_JACOBIAN_MATRIX(DMY_GSPT,PATCH)
								DET_M = .DETERMINANT.JACOB
	! 							PHY_PT = GET_PHY_PT(DMY_GSPT)
								EXDISP = EX_DISP(DMY_GSPT,PATCH)
								CALL APPROXSOL(APDISP, APSTR, DMY_GSPT, COEFF_SOL, PATCH)
								INTF(1)%X = INTF(1)%X + (EXDISP%X - APDISP%X)**2*DET_M*GSXW(KK)*GSYW(K)
								INTF(1)%Y = INTF(1)%Y + (EXDISP%Y - APDISP%Y)**2*DET_M*GSXW(KK)*GSYW(K)
								INTF(2)%X = INTF(2)%X + EXDISP%X**2*DET_M*GSXW(KK)*GSYW(K)
								INTF(2)%Y = INTF(2)%Y + EXDISP%Y**2*DET_M*GSXW(KK)*GSYW(K)
							ENDDO
						ENDDO
					ENDDO
				ENDDO
			ENDDO
		ENDDO
	ENDDO
	
	L2_NORM(1) = DSQRT(INTF(1)%X/INTF(2)%X)*100.D0
	L2_NORM(2) = DSQRT(INTF(1)%Y/INTF(2)%Y)*100.D0
	
! 	OPEN(13, FILE=filename, STATUS='unknown', POSITION='append')
! 	WRITE(13,*) ''
! 	WRITE(13,*) 'RELATIVE ERROR IN L2 NORM (%) OF DISPLACEMENT ALONG X-DIRECTION : ', L2_NORM(1)
! 	WRITE(13,*) 'RELATIVE ERROR IN L2 NORM (%) OF DISPLACEMENT ALONG Y-DIRECTION : ', L2_NORM(2)
! 	CLOSE(1)
	
END SUBROUTINE L2_NORM_ERROR

SUBROUTINE APPROXSOL(APDISP, APSTR, REF_PT, COEFF_SOL, PATCH)

	INTEGER, INTENT(IN) :: PATCH
	TYPE(POINT2D), INTENT(IN) :: REF_PT
	REAL*8, INTENT(IN) :: COEFF_SOL(2*DOF)
	TYPE(POINT2D), INTENT(OUT) :: APDISP
	TYPE(STRESS), INTENT(OUT) :: APSTR
	
	TYPE(FVALUE) :: SF(DOF)
	TYPE(FVALUE) :: LOCAL_IGA_SF(NUM_PATCH,(BASIS_KVEC(1,1)%POLY_ORDER+1)*(BASIS_KVEC(1,2)%POLY_ORDER+1))

	TYPE(INT2D) :: IGA_INDX(NUM_PATCH,(BASIS_KVEC(1,1)%POLY_ORDER+1)*(BASIS_KVEC(1,2)%POLY_ORDER+1))

	TYPE(POINT2D) :: PHY_PT, POLAR_PT, PHYPT_F, INV_PHYPT_G
	TYPE(MATRIX_22) :: JACOB(NUM_PATCH)
	REAL*8 :: DMY_STRAIN(3), APP_STRAIN(3), DMY_STRESS(3), R, THETA
	INTEGER :: I, J, II, JJ, KK, GLOBAL_INDX, LOCAL_DOF_SUM, IGA_PATCH, EGM_PATCH
	LOGICAL :: INTERFACE_MASK
	
	APDISP = POINT2D(0.D0,0.D0)
! 	APDISP = DISPLACEMENT(0.0D0, 0.0D0, 0.0D0)
	APSTR = STRESS(0.0D0, 0.0D0, 0.0D0, 0.D0, 0.D0)
	SF(:) = FVALUE(0.D0,0.D0,0.D0,0.D0,0.D0,0.D0)
	
	DO I = 1, NUM_PATCH
		LOCAL_IGA_SF(I,:) =  FVALUE(0.D0,0.D0,0.D0,0.D0,0.D0,0.D0)
	ENDDO
	
	IF (PATCH.EQ.1) THEN
		LOCAL_DOF_SUM = 0
	ELSE
		LOCAL_DOF_SUM = SUM(LOCAL_DOF(1:PATCH-1))
	ENDIF
	
	DO I=1, NUM_PATCH
		JACOB(I) = GET_JACOBIAN_MATRIX(REF_PT, I)
	ENDDO
	
	DO I = 1, NUM_PATCH
		CALL GET_ALL_PHY_NURBS_SURFACE_2D(LOCAL_IGA_SF(I,:), IGA_INDX(I,:), REF_PT, JACOB(I), I)
	ENDDO
	
	DO I = 1, NUM_PATCH
		DO JJ=1, UBOUND(LOCAL_IGA_SF,2)
			DO II=1, LOCAL_DOF(I)
				IF (PATCH==I .AND. NDX(1,LOCAL_DOF_SUM + II).EQ.IGA_INDX(I,JJ)%A .AND. NDX(2,LOCAL_DOF_SUM + II).EQ.IGA_INDX(I,JJ)%B) THEN
					SF(LOCAL_DOF_SUM + II) = LOCAL_IGA_SF(I,JJ)
					GOTO 1
				ENDIF
			ENDDO
			1 CONTINUE
		ENDDO
	ENDDO

	APDISP%X = DOT_PRODUCT(COEFF_SOL(1:DOF), SF(:)%D00)
	APDISP%Y = DOT_PRODUCT(COEFF_SOL(DOF+1:2*DOF), SF(:)%D00)
	APP_STRAIN = (/0.D0,0.D0,0.D0/)
	DO II=1, DOF
		DMY_STRAIN = (/COEFF_SOL(II)*SF(II)%D10, COEFF_SOL(DOF+II)*SF(II)%D01, COEFF_SOL(II)*SF(II)%D01+ COEFF_SOL(DOF+II)*SF(II)%D10/)
		APP_STRAIN = (/APP_STRAIN(1) + DMY_STRAIN(1),APP_STRAIN(2) + DMY_STRAIN(2),APP_STRAIN(3) + DMY_STRAIN(3)/)
	ENDDO
	DMY_STRESS = MATMUL(STRESS_E, APP_STRAIN)
	APSTR = STRESS(DMY_STRESS(1), DMY_STRESS(2), DMY_STRESS(3), 0.D0, 0.D0)
			
! 			APMOMENT(KK)%MXX = STRESS_D(1,1)*DOT_PRODUCT(COEFF_SOL(DOF+1:2*DOF), SF(:)%D10) + &
! 												 STRESS_D(1,2)*DOT_PRODUCT(COEFF_SOL(2*DOF+1:3*DOF), SF(:)%D01)
! 			APMOMENT(KK)%MYY = STRESS_D(1,2)*DOT_PRODUCT(COEFF_SOL(DOF+1:2*DOF), SF(:)%D10) + &
! 												 STRESS_D(2,2)*DOT_PRODUCT(COEFF_SOL(2*DOF+1:3*DOF), SF(:)%D01)
! 			APMOMENT(KK)%MXY = STRESS_D(3,3)*(DOT_PRODUCT(COEFF_SOL(DOF+1:2*DOF), SF(:)%D01) + &
! 																				DOT_PRODUCT(COEFF_SOL(2*DOF+1:3*DOF), SF(:)%D10))
	
END SUBROUTINE APPROXSOL

! SUBROUTINE STIF_BUGKILLER(STIF_K, STIF_F)
! 
! 	REAL*8, INTENT(IN) :: STIF_K(2*DOF,2*DOF), STIF_F(2*DOF)
! 	
! 	REAL*8 :: STIF_INT(3), LOAD_INT, WEIGHT(NUMGSPT**2), DET_JF, DET_M
! 	TYPE(POINT2D) :: LOAD_F(NUMGSPT**2), GSPT, DMY_GSPT, PHYPT_F, INV_PHYPT_G
! 	TYPE(FVALUE) :: STIF_SF(NUMGSPT**2), STIF_I(NUMGSPT**2), STIF_J(NUMGSPT**2)
! 	INTEGER :: I, J, K, II, JJ, KK, PATCH
! 	TYPE(MATRIX_22) :: JACOB_F, JACOB_G, JACOB
! 	
! 	STIF_SF(:) = FVALUE(0.D0,0.D0,0.D0,0.D0,0.D0,0.D0)
! 	STIF_I(:) = FVALUE(0.D0,0.D0,0.D0,0.D0,0.D0,0.D0)
! 	STIF_J(:) = FVALUE(0.D0,0.D0,0.D0,0.D0,0.D0,0.D0)
! 	STIF_INT(:) = 0.D0; LOAD_INT = 0.D0
! 	
! 	!----- CHECK STIFFNESS MATRIC -----!
! 
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! 	! (1) STIF_K (35,35), STIF_F(35)
! 
! 	CALL GAULEG(0.D0, 1.D0, GSX, GSXW, NUMGSPT)
! 	CALL GAULEG(0.D0, 1.D0, GSY, GSYW, NUMGSPT)
! 	
! ! 	PRINT*, 'BUG - HERE1'
! 	
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! ! 			PRINT*, I, J
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT, 2)
! 			DET_M = .DETERMINANT.JACOB
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 1, 2, JACOB, 2)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 1, 2, JACOB, 2)
! 		ENDDO
! 	ENDDO
! 	
! ! 	PRINT*, 'BUG - HERE2'
! 	
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 
! ! 	PRINT*, STIF_INT(3), STIF_K(35,35)
! 	IF (DABS(STIF_K(35,35) - STIF_INT(3)).GT.EPS) THEN
! 		PRINT*, 'FOUND BUG! - ', 'STIF_K(35,35)', DABS(STIF_K(35,35) - STIF_INT(3))
! 	ENDIF
! 	
! ! 	PRINT*, 'BUG - HERE1'
! 
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! 	! (1) STIF_K (29,29), STIF_F(29)
! 	STIF_INT(:) = 0.D0
! 	CALL GAULEG(0.D0, 1.D0, GSX, GSXW, NUMGSPT)
! 	CALL GAULEG(0.D0, 1.D0, GSY, GSYW, NUMGSPT)
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT, 2)
! 			DET_M = .DETERMINANT.JACOB
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 3, 0, JACOB, 2)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 3, 0, JACOB, 2)
! 		ENDDO
! 	ENDDO
! 
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 
! ! 	PRINT*, 'STIF_INT(1:3)', STIF_INT(1:3)
! 
! 	KK = 0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT, 3)
! 			DET_M = .DETERMINANT.JACOB
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 3, 4, JACOB, 3)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 3, 4, JACOB, 3)
! 		ENDDO
! 	ENDDO
! 
! ! 	PRINT*, 'BUG - HERE2'
! 	
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! ! 	PRINT*, 'STIF_INT(1:3)', STIF_INT(1:2), SUM(STIF_INT(1:2))
! 
! ! 	PRINT*, STIF_INT(3), STIF_K(29,29)
! 	IF (DABS(STIF_K(29,29) - STIF_INT(3)).GT.EPS) THEN
! 		PRINT*, 'FOUND BUG! - ', 'STIF_K(29,29)', DABS(STIF_K(29,29) - STIF_INT(3))
! 	ENDIF
! 
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! 	! (1) STIF_K (29,27)
! 	STIF_INT(:) = 0.D0
! 	CALL GAULEG(0.D0, 1.D0, GSX, GSXW, NUMGSPT)
! 	CALL GAULEG(0.D0, 1.D0, GSY, GSYW, NUMGSPT)
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! ! 			PRINT*, I, J
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT, 2)
! 			DET_M = .DETERMINANT.JACOB
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 3, 0, JACOB, 2)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 1, 0, JACOB, 2)
! 		ENDDO
! 	ENDDO
! 	
! ! 	PRINT*, 'BUG - HERE2'
! 	
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! 	KK = 0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! ! 			PRINT*, I, J
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT, 3)
! 			DET_M = .DETERMINANT.JACOB
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 3, 4, JACOB, 3)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 1, 4, JACOB, 3)
! 		ENDDO
! 	ENDDO
! 	
! ! 	PRINT*, 'BUG - HERE2'
! 	
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! ! 	PRINT*, STIF_INT(3), STIF_K(29,27)
! 	IF (DABS(STIF_K(29,27) - STIF_INT(3)).GT.EPS) THEN
! 		PRINT*, 'FOUND BUG! - ', 'STIF_K(29,27)', DABS(STIF_K(29,27) - STIF_INT(3))
! 	ENDIF
! 
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! 	! (1) STIF_K (60,60)
! 	STIF_INT(:) = 0.D0
! 	CALL GAULEG(0.D0, 1.D0, GSX, GSXW, NUMGSPT)
! 	CALL GAULEG(0.D0, 1.D0, GSY, GSYW, NUMGSPT)
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! ! 			PRINT*, I, J
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT, 3)
! 			DET_M = .DETERMINANT.JACOB
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 4, 2, JACOB, 3)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 4, 2, JACOB, 3)
! 		ENDDO
! 	ENDDO
! 	
! ! 	PRINT*, 'BUG - HERE2'
! 	
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! 	KK = 0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! ! 			PRINT*, I, J
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT, 4)
! 			DET_M = .DETERMINANT.JACOB
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 0, 2, JACOB, 4)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 0, 2, JACOB, 4)
! 		ENDDO
! 	ENDDO
! 	
! ! 	PRINT*, 'BUG - HERE2'
! 	
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! ! 	PRINT*, STIF_INT(3), STIF_K(60,60)
! 	IF (DABS(STIF_K(60,60) - STIF_INT(3)).GT.EPS) THEN
! 		PRINT*, 'FOUND BUG! - ', 'STIF_K(60,60)', DABS(STIF_K(60,60) - STIF_INT(3))
! 	ENDIF
! 
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! 	! (1) STIF_K (56,60), STIF_F(4)
! 	STIF_INT(:) = 0.D0
! 	CALL GAULEG(0.D0, 1.D0, GSX, GSXW, NUMGSPT)
! 	CALL GAULEG(0.D0, 1.D0, GSY, GSYW, NUMGSPT)
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! ! 			PRINT*, I, J
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT, 3)
! 			DET_M = .DETERMINANT.JACOB
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 0, 2, JACOB, 3)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 4, 2, JACOB, 3)
! 		ENDDO
! 	ENDDO
! 	
! ! 	PRINT*, 'BUG - HERE2'
! 	
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! ! 	PRINT*, STIF_INT(3), STIF_K(56,60)
! 	IF (DABS(STIF_K(56,60) - STIF_INT(3)).GT.EPS) THEN
! 		PRINT*, 'FOUND BUG! - ', 'STIF_K(56,60)', DABS(STIF_K(56,60) - STIF_INT(3))
! 	ENDIF
! 	
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! 	! (1) STIF_K (6,16), STIF_F(4)
! 	STIF_INT(:) = 0.D0
! 	CALL GAULEG(0.D0, 1.D0, GSX, GSXW, NUMGSPT)
! 	CALL GAULEG(0.D0, 1.D0, GSY, GSYW, NUMGSPT)
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! ! 			PRINT*, I, J
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT, 1)
! 			DET_M = .DETERMINANT.JACOB
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 0, 1, JACOB, 1)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 0, 3, JACOB, 1)
! 		ENDDO
! 	ENDDO
! 	
! ! 	PRINT*, 'BUG - HERE2'
! 	
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! ! 			PRINT*, I, J
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT, 2)
! 			DET_M = .DETERMINANT.JACOB
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 4, 1, JACOB, 2)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 4, 3, JACOB, 2)
! 		ENDDO
! 	ENDDO
! 	
! ! 	PRINT*, 'BUG - HERE2'
! 	
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! ! 	PRINT*, STIF_INT(3), STIF_K(6,16)
! 	IF (DABS(STIF_K(6,16) - STIF_INT(3)).GT.EPS) THEN
! 		PRINT*, 'FOUND BUG! - ', 'STIF_K(6,16)', DABS(STIF_K(6,16) - STIF_INT(3))
! 	ENDIF
! 	
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! 	! (1) STIF_K (133,133), STIF_F(133)
! 	STIF_INT(:) = 0.D0
! 	CALL GAULEG(0.75D0, 1.D0, GSX, GSXW, NUMGSPT)
! 	CALL GAULEG(0.D0, 0.9D0, GSY, GSYW, NUMGSPT)
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! ! 			PRINT*, I, J
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT, 5)
! 			DET_M = .DETERMINANT.JACOB
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 13, 2, JACOB, 5)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 13, 2, JACOB, 5)
! 		ENDDO
! 	ENDDO
! 	
! ! 	PRINT*, 'BUG - HERE2'
! 	
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! ! 	PRINT*, STIF_INT(3), STIF_K(133,133)
! 	IF (DABS(STIF_K(133,133) - STIF_INT(3)).GT.EPS) THEN
! 		PRINT*, 'FOUND BUG! - ', 'STIF_K(133,133)', DABS(STIF_K(133,133) - STIF_INT(3))
! 	ENDIF
! 	
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! 	! (1) STIF_K (150,6), STIF_F(150)
! 	STIF_INT(:) = 0.D0
! 	CALL GAULEG(0.75D0, 1.D0, GSX, GSXW, NUMGSPT)
! 	CALL GAULEG(0.D0, 0.9D0, GSY, GSYW, NUMGSPT)
! 	
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! ! 			PRINT*, I, J
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			PHYPT_F = GET_PHY_PT(DMY_GSPT,5)
! 			INV_PHYPT_G = GET_REF_PT(PHYPT_F,1)
! 			JACOB_F = GET_JACOBIAN_MATRIX(DMY_GSPT,5)
! 			JACOB_G = GET_JACOBIAN_MATRIX(INV_PHYPT_G,1)
! 			DET_M = .DETERMINANT.JACOB_F
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(INV_PHYPT_G, 0, 1, JACOB_G, 1)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 13, 3, JACOB_F, 5)
! 		ENDDO
! 	ENDDO
! 
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! 	CALL GAULEG(0.75D0, 1.D0, GSX, GSXW, NUMGSPT)
! 	CALL GAULEG(0.9D0, 1.D0, GSY, GSYW, NUMGSPT)
! 	
! ! 	PRINT*, STIF_INT(3)
! 	
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			PHYPT_F = GET_PHY_PT(DMY_GSPT,5)
! 			INV_PHYPT_G = GET_REF_PT(PHYPT_F,1)
! 			JACOB_F = GET_JACOBIAN_MATRIX(DMY_GSPT,5)
! 			JACOB_G = GET_JACOBIAN_MATRIX(INV_PHYPT_G,1)
! 			DET_M = .DETERMINANT.JACOB_F
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(INV_PHYPT_G, 0, 1, JACOB_G, 1)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 13, 3, JACOB_F, 5)
! 		ENDDO
! 	ENDDO
! 
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! ! 	PRINT*, STIF_INT(3), STIF_K(150,6)
! 	IF (DABS(STIF_K(150,6) - STIF_INT(3)).GT.EPS) THEN
! 		PRINT*, 'FOUND BUG! - ', 'STIF_K(150,6)', DABS(STIF_K(150,6) - STIF_INT(3))
! 	ENDIF
! 	
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! 	! (1) STIF_K (104,71), STIF_F(4)
! 	STIF_INT(:) = 0.D0
! 	CALL GAULEG(0.D0, 0.25D0, GSX, GSXW, NUMGSPT)
! 	CALL GAULEG(0.D0, 0.9D0, GSY, GSYW, NUMGSPT)
! 	
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! ! 			PRINT*, I, J
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			PHYPT_F = GET_PHY_PT(DMY_GSPT,5)
! 			INV_PHYPT_G = GET_REF_PT(PHYPT_F,4)
! 			JACOB_F = GET_JACOBIAN_MATRIX(DMY_GSPT,5)
! 			JACOB_G = GET_JACOBIAN_MATRIX(INV_PHYPT_G,4)
! 			DET_M = .DETERMINANT.JACOB_F
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(INV_PHYPT_G, 2, 1, JACOB_G, 4)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 1, 1, JACOB_F, 5)
! 		ENDDO
! 	ENDDO
! 
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! ! 	PRINT*, STIF_INT(3), STIF_K(104,71)
! 	IF (DABS(STIF_K(104,71) - STIF_INT(3)).GT.EPS) THEN
! 		PRINT*, 'FOUND BUG! - ', 'STIF_K(104,71)', DABS(STIF_K(104,71) - STIF_INT(3))
! 	ENDIF
! 	
! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! 	! (1) STIF_K (107,55), STIF_F(21)
! 	STIF_INT(:) = 0.D0
! 	CALL GAULEG(0.D0, 0.25D0, GSX, GSXW, NUMGSPT)
! 	CALL GAULEG(0.D0, 0.9D0, GSY, GSYW, NUMGSPT)
! 	
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! ! 			PRINT*, I, J
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			PHYPT_F = GET_PHY_PT(DMY_GSPT,5)
! 			INV_PHYPT_G = GET_REF_PT(PHYPT_F,4)
! 			JACOB_F = GET_JACOBIAN_MATRIX(DMY_GSPT,5)
! 			JACOB_G = GET_JACOBIAN_MATRIX(INV_PHYPT_G,4)
! 			DET_M = .DETERMINANT.JACOB_F
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(INV_PHYPT_G, 0, 1, JACOB_G, 4)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 4, 1, JACOB_F, 5)
! 		ENDDO
! 	ENDDO
! 
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 	
! 	CALL GAULEG(0.25D0, 0.5D0, GSX, GSXW, NUMGSPT)
! 	CALL GAULEG(0.D0, 0.9D0, GSY, GSYW, NUMGSPT)
! 	
! ! 	PRINT*, STIF_INT(3)
! 	
! 	KK=0
! 	DO I=1,NUMGSPT
! 		DO J=1,NUMGSPT
! 			KK=KK+1
! 			GSPT = POINT2D(GSX(I), GSY(J))
! 			DMY_GSPT = GSPT
! 			PHYPT_F = GET_PHY_PT(DMY_GSPT,5)
! 			INV_PHYPT_G = GET_REF_PT(PHYPT_F,3)
! 			JACOB_F = GET_JACOBIAN_MATRIX(DMY_GSPT,5)
! 			JACOB_G = GET_JACOBIAN_MATRIX(INV_PHYPT_G,3)
! 			DET_M = .DETERMINANT.JACOB_F
! 			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			STIF_I(KK) = GET_PHY_BASIS_IN_INT(INV_PHYPT_G, 4, 1, JACOB_G, 3)
! 			STIF_J(KK) = GET_PHY_BASIS_IN_INT(DMY_GSPT, 4, 1, JACOB_F, 5)
! 		ENDDO
! 	ENDDO
! 
! 	STIF_INT(1) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D10)
! 	STIF_INT(2) = DOT_PRODUCT(PRODUCT(RESHAPE((/STIF_I(:)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), STIF_J(:)%D01)
! 	STIF_INT(3) = STIF_INT(3) + SUM(STIF_INT(1:2))
! 		
! ! 	PRINT*, STIF_INT(3), STIF_K(107,55)
! 	IF (DABS(STIF_K(107,55) - STIF_INT(3)).GT.EPS) THEN
! 		PRINT*, 'FOUND BUG! - ', 'STIF_K(107,55)', DABS(STIF_K(107,55) - STIF_INT(3))
! 	ENDIF
! 	
! END SUBROUTINE STIF_BUGKILLER

END MODULE ERRORESTIMATE
