! NAME : HYUNJU KIM
! DATE : 11 / 8 / 2010

MODULE GLBVAR

	USE NEWTYPE

  IMPLICIT NONE

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!   GLOBAL PARAMETER

	REAL(8), PARAMETER :: PI=DACOS(-1.0D0)
	REAL(8), PARAMETER :: DEGREE = PI/180.D0
	REAL(8), PARAMETER:: EPS=5.0D-15
	INTEGER :: PROBLEM

	! B-SPLINE GLOBAL VARIABLES
	INTEGER, PARAMETER :: NUM_PATCH = 1

	INTEGER :: IGA_ORDER(2), EXTRA_KNOTS(2), NURBS_REGULARITY(2)
	INTEGER :: NUMBS(NUM_PATCH,2), DOF, LOCAL_DOF(NUM_PATCH), BD_DOF

	INTEGER, PARAMETER :: NM_NUMBD = 6, DR_NUMBD = NUM_PATCH
	TYPE(BD_INFO) :: NM_BDNDX(NM_NUMBD,MAX_LENGTH), DR_BDNDX(DR_NUMBD,MAX_LENGTH)
	LOGICAL, ALLOCATABLE :: BD_MASK(:)

	!! DUMMY VARIABLES
	INTEGER :: FULL_LOCAL_DOF(NUM_PATCH)
	
	
	!!  VARIABLES FOR GEOMETRIC MAP
	TYPE(KNOT_VECTOR), SAVE :: GEO_KVEC(NUM_PATCH,2), IGA_KVEC(NUM_PATCH,2), BASIS_KVEC(NUM_PATCH,2)
	TYPE(CONTROL_POINTS_2D) :: GEO_CTL(NUM_PATCH), IGA_CTL(NUM_PATCH)

		!!  CONNECTIVITY ARRAY
	INTEGER, ALLOCATABLE :: CARRAY(:,:)
	
	!!  BINOMIAL COEFFICIENTS
	REAL(8) :: BINOM(MAX_DIFF_ORDER,0:MAX_DIFF_ORDER)

	! INTEGRAL GLOBAL VARIABLES
	INTEGER :: NUMGSPT
	REAL*8 :: IR_GRID(NUM_PATCH, 2, MAX_LENGTH)
	INTEGER :: NUMIR(NUM_PATCH,2), LN_NUMGSPT

	REAL*8, ALLOCATABLE :: GSX(:), GSXW(:), GSY(:), GSYW(:)
	REAL*8, ALLOCATABLE :: WEIGHT(:)

	INTEGER, ALLOCATABLE :: NDX(:,:), DMY_NDX(:,:)
	TYPE(INTERFACE_INFO), ALLOCATABLE :: INTERFACE_NDX(:), INTERFACE_BDNDX(:)

	CHARACTER(LEN=2) :: CHAR_ORDER(2)
	CHARACTER(LEN=2) :: CHAR_BASIS(2)
	CHARACTER(LEN=5) :: CHAR_KNOT_INTERVAL(2)
	CHARACTER(LEN=2) :: CHAR_SPE_CONST
	CHARACTER(LEN=2) :: CHAR_GEO_CONST
	CHARACTER(LEN=1) :: CHAR_PROBLEM
	CHARACTER(LEN=100) :: FILENAME
	
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	INTEGER, DIMENSION(1:2), PARAMETER :: ORDER1=(/ 1, 2 /)
	INTEGER, DIMENSION(1:2), PARAMETER :: ORDER2=(/ 2, 1 /)

!	MATERIAL COEFFICIENTS

	CHARACTER(LEN=5) :: BCTYPE

	
	REAL*8, PARAMETER :: E = 1000.0D0 					! YOUNG'S MODULUS {E1, E2}, STEEL
	REAL*8, PARAMETER :: V = 0.30D0		  				! POISSON RATION {V12, V21}
	REAL*8, PARAMETER :: SIGMA = 100.D0
	REAL*8, PARAMETER :: LENGTH_CRACK = 2.D0
	REAL*8, PARAMETER :: LENGTH_DOMAIN = 4.D0
	REAL*8, PARAMETER :: LAMBDA = 0.544483737D0
	REAL*8, PARAMETER :: MU = E/(2.D0*(1.D0+V)) ! RIGIDITY MODULUS
	REAL*8, PARAMETER :: Q = -DCOS((LAMBDA-1.D0)*135.D0*DEGREE)/DCOS((LAMBDA+1.D0)*135.D0*DEGREE)

	!! PLANE STRESS
! 	CHARACTER(LEN=6), PARAMETER :: PLANE_TYPE = 'stress'
! 	REAL*8, PARAMETER :: KAPPA = (3.D0-V)/(1.D0+V)	
! 	REAL*8, PARAMETER :: STRESS_E33 = MU
! 	REAL*8, PARAMETER :: STRESS_E11 = E/(1.D0-V**2)
! 	REAL*8, PARAMETER :: STRESS_E22 = STRESS_E11
! 	REAL*8, PARAMETER :: STRESS_E12 = V*STRESS_E11
! 	REAL*8, PARAMETER :: STRESS_E21 = V*STRESS_E11

	!! PLANE STRAIN
	CHARACTER(LEN=6), PARAMETER :: PLANE_TYPE = 'strain'
	REAL*8, PARAMETER :: KAPPA = 3.D0 - 4.D0*V
	REAL*8, PARAMETER :: STRESS_E33 = MU
	REAL*8, PARAMETER :: STRESS_E11 = E*(1.D0-V)/((1.D0+V)*(1.D0-2.D0*V))
	REAL*8, PARAMETER :: STRESS_E22 = STRESS_E11
	REAL*8, PARAMETER :: STRESS_E12 = (V/(1.D0-V))*STRESS_E11
	REAL*8, PARAMETER :: STRESS_E21 = (V/(1.D0-V))*STRESS_E11

	REAL*8, DIMENSION(3,3), PARAMETER :: STRESS_E = RESHAPE((/ STRESS_E11,STRESS_E12,0.D0,STRESS_E21,STRESS_E22,0.D0,0.D0,0.D0,STRESS_E33/), (/ 3, 3 /), ORDER=ORDER2)

!		Center - Cracked Stress Intensity Factor
! 	REAL*8, PARAMETER :: KI = SIGMA*DSQRT(PI*HALF_LENGTH_CRACK)*(1.D0 + 0.128D0*(HALF_LENGTH_CRACK/HALF_LENGTH_DOMAIN) + 0.288D0*(HALF_LENGTH_CRACK/HALF_LENGTH_DOMAIN)**2 + 1.523D0*(HALF_LENGTH_CRACK/HALF_LENGTH_DOMAIN)**3)

!		Single - Edged - Cracked Stress Intensity Factor
	REAL*8, PARAMETER :: KI = SIGMA*DSQRT(PI*LENGTH_CRACK)*(1.12D0 - 0.23D0*(LENGTH_CRACK/LENGTH_DOMAIN) + 10.55D0*(LENGTH_CRACK/LENGTH_DOMAIN)**2 - 21.72D0*(LENGTH_CRACK/LENGTH_DOMAIN)**3 + 30.39D0*(LENGTH_CRACK/LENGTH_DOMAIN)**4)

	TYPE(POINT2D), PARAMETER :: PT0 = POINT2D(0.D0,0.D0)

END MODULE GLBVAR
