	MODULE INTEGRATION

	USE GSQUAD
	USE NURBS_BASIS
	USE LOADFUNCTION

	implicit integer (i-n)
	implicit real(8) (a-h,o-z)

CONTAINS



!------------------INTEGRAL CODE FOR THE STIFFNESS MATRIX ELEMENT--------------
SUBROUTINE GEN_KF(STIF_K, LOAD_F)

	REAL*8, INTENT(OUT) :: STIF_K(DOF, DOF), LOAD_F(DOF)
	TYPE(RECPATCH) :: IRBOX
	TYPE(POINT2D) :: GSPT, DMY_GSPT
	TYPE(INT2D) :: INDX((BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1))
	TYPE(MATRIX_22) :: JACOB
	TYPE(FVALUE) :: SF(NUMGSPT**2, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1))
	INTEGER :: I,J, II, JJ, KK, N, GLOBAL_INDX(2)
	REAL*8 :: DIFF_XX, DIFF_YY, DIFF_XY, DIFF_YX, DIFF_XN, DIFF_YN, DIFF_NX, DIFF_NY, DIFF_NN, DET_M, WEIGHT(NUMGSPT**2), LOAD_Q_VEC(NUMGSPT**2)
	
	STIF_K(:,:) = 0.D0; LOAD_F(:) = 0.D0
	N = NUMGSPT
	DO JJ=1, NUMIR(2)-1
		DO II=1, NUMIR(1)-1
			IRBOX%PT1 = POINT2D(IR_GRID(1,II), IR_GRID(2,JJ))
			IRBOX%PT2 = POINT2D(IR_GRID(1,II+1), IR_GRID(2,JJ))
			IRBOX%PT3 = POINT2D(IR_GRID(1,II+1), IR_GRID(2,JJ+1))
			IRBOX%PT4 = POINT2D(IR_GRID(1,II), IR_GRID(2,JJ+1))
			!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
			CALL GAULEG(IRBOX%PT1%X, IRBOX%PT2%X, GSX, GSXW, NUMGSPT)
			CALL GAULEG(IRBOX%PT1%Y, IRBOX%PT4%Y, GSY, GSYW, NUMGSPT)
			KK=0
			DO I=1,N
				DO J=1,N
					KK=KK+1
					GSPT = POINT2D(GSX(I), GSY(J))
					DMY_GSPT = GSPT
					JACOB = GET_JACOBIAN_MATRIX(GSPT)
					DET_M = .DETERMINANT.JACOB
					WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
					LOAD_Q_VEC(KK) = LDFT2D(GSPT)
					CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF(KK,:), INDX, DMY_GSPT, JACOB)
				ENDDO
			ENDDO
			!--------------------EVALUATE INTEGRAND AT EACH GAUSS POINT IN SUBMATRIX-----------
			DO I = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
				DO KK=1, DOF
					IF (NDX(1,KK).EQ.INDX(I)%A .AND. NDX(2,KK).EQ.INDX(I)%B) THEN
						GLOBAL_INDX(1) = KK
						GOTO 111
					ENDIF
				ENDDO
				111 CONTINUE
				DO J = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
					DO KK=1, DOF
						IF (NDX(1,KK).EQ.INDX(J)%A .AND. NDX(2,KK).EQ.INDX(J)%B) THEN
							GLOBAL_INDX(2) = KK
							GOTO 222
						ENDIF
					ENDDO
					222 CONTINUE
! 					DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF(:,J)%D00)
					DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF(:,J)%D10)
					DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF(:,J)%D01)
! 					DIFF_NX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF(:,J)%D10)
! 					DIFF_NY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF(:,J)%D01)
! 					DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF(:,J)%D10)
! 					DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF(:,J)%D01)
					
					STIF_K(GLOBAL_INDX(2),GLOBAL_INDX(1)) = STIF_K(GLOBAL_INDX(2),GLOBAL_INDX(1)) + DIFF_XX + DIFF_YY
				ENDDO
				DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), LOAD_Q_VEC(:))
				LOAD_F(GLOBAL_INDX(1)) = LOAD_F(GLOBAL_INDX(1)) + DIFF_NN
			ENDDO
		ENDDO
	ENDDO
	
	WRITE(*,*)
	WRITE(*,*) '<<< ASSEMBLE STIFFNESS MATRIX AND LOAD VECTOR : DONE >>>'
	WRITE(*,*)
	
END SUBROUTINE GEN_KF

SUBROUTINE GEN_BD_LN(SUB_K, SUB_F)

	REAL*8, INTENT(OUT) :: SUB_K(BDNDX(1)%LC_NUM, BDNDX(1)%LC_NUM)
	REAL*8, INTENT(OUT) :: SUB_F(BDNDX(1)%LC_NUM)
	
	REAL*8 :: EXACT_ON_BD(NUMGSPT), WEIGHT(NUMGSPT), DIFF_NN, DET_M
	TYPE(FVALUE) :: SF(NUMGSPT, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1))
	TYPE(INT2D) :: INDX((BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1))
	TYPE(POINT2D) :: GSPT, DMY_GSPT
	INTEGER :: I, J, II, JJ, KK, N, GLOBAL_INDX(2)
	TYPE(VEC2D) :: SUB_LN
	TYPE(MATRIX_22) :: JACOB
	CHARACTER(LEN=1) :: GAMMA_HAT
	
	N = NUMGSPT; SUB_K(:,:)=0.D0; SUB_F(:) = 0.D0

!------------------------- LEFT ----------------------------------
	DO JJ = 1, NUMIR(2)-1
		SUB_LN = VEC2D(POINT2D(0.D0,IR_GRID(2,JJ)), POINT2D(0.D0,IR_GRID(2,JJ+1)))
		DIFF_NN = 0.D0
		CALL GAULEG(SUB_LN%U%Y, SUB_LN%V%Y, GSY, GSYW, NUMGSPT)
		DO I=1,N
			GSPT = POINT2D(0.D0, GSY(I))
			DMY_GSPT = GSPT
			JACOB = GET_JACOBIAN_MATRIX(GSPT)
			GAMMA_HAT = GET_GAMMA_HAT(GSPT)
			DET_M = GET_DET_DR(GSPT, GAMMA_HAT)
			WEIGHT(I) = DET_M*GSYW(I)
			CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF(I,:), INDX, DMY_GSPT, JACOB)
			EXACT_ON_BD(I) = EX_DISP(DMY_GSPT)
		ENDDO
! 		PRINT*, 'HERE-1'
		DO I = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
			DO KK=1, BDNDX(1)%LC_NUM
				IF (BDNDX(KK)%LC_NDX(1).EQ.INDX(I)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX(I)%B) THEN
					GLOBAL_INDX(1) = KK
					GOTO 111
				ENDIF
			ENDDO
			GOTO 112
! 			print*, 'here-2'
			111 CONTINUE
			DO J = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
				DO KK=1, BDNDX(1)%LC_NUM
					IF (BDNDX(KK)%LC_NDX(1).EQ.INDX(J)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX(J)%B) THEN
						GLOBAL_INDX(2) = KK
						GOTO 222
					ENDIF
				ENDDO
				GOTO 223
! 				print*, 'here-3'
				222 CONTINUE
				DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), SF(:,J)%D00)
				SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
				223 CONTINUE
			ENDDO
			
			DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:))
			SUB_F(GLOBAL_INDX(1)) = SUB_F(GLOBAL_INDX(1)) + DIFF_NN
			112 CONTINUE
		ENDDO
! 		PRINT*, 'HERE-4'
	ENDDO

!------------------------- RIGHT ----------------------------------
	DO JJ = 1, NUMIR(2)-1
		SUB_LN = VEC2D(POINT2D(1.D0,IR_GRID(2,JJ)), POINT2D(1.D0,IR_GRID(2,JJ+1)))
		DIFF_NN = 0.D0
		CALL GAULEG(SUB_LN%U%Y, SUB_LN%V%Y, GSY, GSYW, NUMGSPT)
		DO I=1,N
			GSPT = POINT2D(1.D0, GSY(I))
			DMY_GSPT = GSPT
			GAMMA_HAT = GET_GAMMA_HAT(GSPT)
			DET_M = GET_DET_DR(GSPT, GAMMA_HAT)
			WEIGHT(I) = DET_M*GSYW(I)
			CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF(I,:), INDX, DMY_GSPT, JACOB)
			EXACT_ON_BD(I) = EX_DISP(DMY_GSPT)
		ENDDO
		DO I = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
			DO KK=1, BDNDX(1)%LC_NUM
				IF (BDNDX(KK)%LC_NDX(1).EQ.INDX(I)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX(I)%B) THEN
					GLOBAL_INDX(1) = KK
					GOTO 333
				ENDIF
			ENDDO
			GOTO 334
			333 CONTINUE
			DO J = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
				DO KK=1, BDNDX(1)%LC_NUM
					IF (BDNDX(KK)%LC_NDX(1).EQ.INDX(J)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX(J)%B) THEN
						GLOBAL_INDX(2) = KK
						GOTO 444
					ENDIF
				ENDDO
				GOTO 445
				444 CONTINUE
				DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), SF(:,J)%D00)
				SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
				445 CONTINUE
			ENDDO
			DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:))
			SUB_F(GLOBAL_INDX(1)) = SUB_F(GLOBAL_INDX(1)) + DIFF_NN
			334 CONTINUE
		ENDDO
	ENDDO

!------------------------- BOTTOM ----------------------------------
	DO JJ = 1, NUMIR(1)-1
		SUB_LN = VEC2D(POINT2D(IR_GRID(1,JJ),0.D0), POINT2D(IR_GRID(1,JJ+1),0.D0))
		DIFF_NN = 0.D0
		CALL GAULEG(SUB_LN%U%X, SUB_LN%V%X, GSX, GSXW, NUMGSPT)
		DO I=1,N
			GSPT = POINT2D(GSX(I),0.D0)
			DMY_GSPT = GSPT
			JACOB = GET_JACOBIAN_MATRIX(GSPT)
			GAMMA_HAT = GET_GAMMA_HAT(GSPT)
			DET_M = GET_DET_DR(GSPT, GAMMA_HAT)
			WEIGHT(I) = DET_M*GSXW(I)
			CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF(I,:), INDX, DMY_GSPT, JACOB)
			EXACT_ON_BD(I) = EX_DISP(DMY_GSPT)
		ENDDO
		DO I = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
			DO KK=1, BDNDX(1)%LC_NUM
				IF (BDNDX(KK)%LC_NDX(1).EQ.INDX(I)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX(I)%B) THEN
					GLOBAL_INDX(1) = KK
					GOTO 555
				ENDIF
			ENDDO
			GOTO 556
			555 CONTINUE
			DO J = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
				DO KK=1, BDNDX(1)%LC_NUM
					IF (BDNDX(KK)%LC_NDX(1).EQ.INDX(J)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX(J)%B) THEN
						GLOBAL_INDX(2) = KK
						GOTO 666
					ENDIF
				ENDDO
				GOTO 667
				666 CONTINUE
				DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), SF(:,J)%D00)
				SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
				667 CONTINUE
			ENDDO
			DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:))
			SUB_F(GLOBAL_INDX(1)) = SUB_F(GLOBAL_INDX(1)) + DIFF_NN
			556 CONTINUE
		ENDDO
	ENDDO

!------------------------- TOP ----------------------------------
	DO JJ = 1, NUMIR(1)-1
		SUB_LN = VEC2D(POINT2D(IR_GRID(1,JJ),1.D0), POINT2D(IR_GRID(1,JJ+1),1.D0))
		DIFF_NN = 0.D0
		CALL GAULEG(SUB_LN%U%X, SUB_LN%V%X, GSX, GSXW, NUMGSPT)
		DO I=1,N
			GSPT = POINT2D(GSX(I),1.D0)
			DMY_GSPT = GSPT
			JACOB = GET_JACOBIAN_MATRIX(GSPT)
			GAMMA_HAT = GET_GAMMA_HAT(GSPT)
			DET_M = GET_DET_DR(GSPT, GAMMA_HAT)
			WEIGHT(I) = DET_M*GSXW(I)
			CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF(I,:), INDX, DMY_GSPT, JACOB)
			EXACT_ON_BD(I) = EX_DISP(DMY_GSPT)
		ENDDO
		DO I = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
			DO KK=1, BDNDX(1)%LC_NUM
				IF (BDNDX(KK)%LC_NDX(1).EQ.INDX(I)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX(I)%B) THEN
					GLOBAL_INDX(1) = KK
					GOTO 777
				ENDIF
			ENDDO
			GOTO 778
			777 CONTINUE
			DO J = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
				DO KK=1, BDNDX(1)%LC_NUM
					IF (BDNDX(KK)%LC_NDX(1).EQ.INDX(J)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX(J)%B) THEN
						GLOBAL_INDX(2) = KK
						GOTO 888
					ENDIF
				ENDDO
				GOTO 889
				888 CONTINUE
				DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), SF(:,J)%D00)
				SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
				889 CONTINUE
			ENDDO
			DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:))
			SUB_F(GLOBAL_INDX(1)) = SUB_F(GLOBAL_INDX(1)) + DIFF_NN
			778 CONTINUE
		ENDDO
	ENDDO
		
END SUBROUTINE GEN_BD_LN

END MODULE INTEGRATION
