MODULE PATCH_MAPPING

	USE NURBS

	implicit integer (i-n)
	implicit real(8) (a-h,o-z)

CONTAINS

	!!  GET THE CORRESPONDING POINT ON THE PHYSICAL SPACE OF GIVE POINT ON THE PARAMETRIC SPACE
	TYPE(POINT2D) FUNCTION GET_PHY_PT(REF_PT)

		TYPE(POINT2D), INTENT(IN) :: REF_PT
		INTEGER :: ITER

		GET_PHY_PT = GET_POINT_NURVE_SURFACE_2D(REF_PT,GEO_KVEC,GEO_CTL)

	END FUNCTION GET_PHY_PT


	!!  GET THE CORRESPONDING POINT ON THE PARAMETRIC SPACE OF GIVE POINT ON THE PHYSICAL SPACE
	TYPE(POINT2D) FUNCTION GET_REF_PT(PHY_PT)

		TYPE(POINT2D), INTENT(IN) :: PHY_PT

		TYPE(FUNCTION_2D) :: DIFF_NURBS(2)
		TYPE(POINT2D) :: NEW_PT, OLD_PT, TMP_PT
		REAL(8) :: ERROR, INV_J
		INTEGER :: ITER

		ERROR = 1.0D0
		OLD_PT = POINT2D(0.D0,0.D0)
		ITER = 0
		DO WHILE (ERROR>TOLERANCE)
			ITER = ITER + 1
! 			PRINT*, 'OLD_PT : ', OLD_PT
			CALL GET_DIFF_NURVE_SURFACE_2D(DIFF_NURBS,OLD_PT,GEO_KVEC,GEO_CTL,1)
			TMP_PT%X = DIFF_NURBS(1)%VAL(0,0)-PHY_PT%X
			TMP_PT%Y = DIFF_NURBS(2)%VAL(0,0)-PHY_PT%Y
			ERROR = MAX(DABS(TMP_PT%X),DABS(TMP_PT%Y))
			IF (ERROR<TOLERANCE) THEN
				GET_REF_PT = OLD_PT
				GOTO 999
			ELSE
				INV_J = 1.0D0 / (DIFF_NURBS(1)%VAL(1,0)*DIFF_NURBS(2)%VAL(0,1)-DIFF_NURBS(1)%VAL(0,1)*DIFF_NURBS(2)%VAL(1,0))
				NEW_PT%X = OLD_PT%X - INV_J*(DIFF_NURBS(2)%VAL(0,1)*TMP_PT%X-DIFF_NURBS(1)%VAL(0,1)*TMP_PT%Y)
				NEW_PT%Y = OLD_PT%Y - INV_J*(DIFF_NURBS(1)%VAL(1,0)*TMP_PT%Y-DIFF_NURBS(2)%VAL(1,0)*TMP_PT%X)
				OLD_PT = NEW_PT
			ENDIF
		ENDDO
		IF (ITER==MAX_ITERATION) THEN
			PRINT *, '[ERROR]  CANNOT FIND REFERENCE POINT !'
		ENDIF

		999 CONTINUE

	END FUNCTION GET_REF_PT


	!!  GET JACOBIAN OF THE GEOMETRIC MAPPING
	TYPE(MATRIX_22) FUNCTION GET_JACOBIAN_MATRIX(REF_PT)

		TYPE(POINT2D), INTENT(IN) :: REF_PT

		TYPE(FUNCTION_2D) :: DIFF_NURBS(2)

		integer :: ix, iy, k

		CALL GET_DIFF_NURVE_SURFACE_2D(DIFF_NURBS,REF_PT,GEO_KVEC,GEO_CTL,1)

		GET_JACOBIAN_MATRIX%ENT(1,1) = DIFF_NURBS(1)%VAL(1,0)
		GET_JACOBIAN_MATRIX%ENT(1,2) = DIFF_NURBS(1)%VAL(0,1)
		GET_JACOBIAN_MATRIX%ENT(2,1) = DIFF_NURBS(2)%VAL(1,0)
		GET_JACOBIAN_MATRIX%ENT(2,2) = DIFF_NURBS(2)%VAL(0,1)

	END FUNCTION GET_JACOBIAN_MATRIX
	
	!!  GET SECOND-ORDER PARTIAL DERIVATIVES
	TYPE(SECOND_PARTIAL_DERIVATIVES) FUNCTION GET_PARTIAL(REF_PT)

		TYPE(POINT2D), INTENT(IN) :: REF_PT

		TYPE(FUNCTION_2D) :: DIFF_NURBS(2)

		CALL GET_DIFF_NURVE_SURFACE_2D(DIFF_NURBS,REF_PT,GEO_KVEC,GEO_CTL,2)

		GET_PARTIAL%X(1) = DIFF_NURBS(1)%VAL(2,0)
		GET_PARTIAL%X(2) = DIFF_NURBS(1)%VAL(1,1)
		GET_PARTIAL%X(3) = DIFF_NURBS(1)%VAL(0,2)

		GET_PARTIAL%Y(1) = DIFF_NURBS(2)%VAL(2,0)
		GET_PARTIAL%Y(2) = DIFF_NURBS(2)%VAL(1,1)
		GET_PARTIAL%Y(3) = DIFF_NURBS(2)%VAL(0,2)

	END FUNCTION GET_PARTIAL

	REAL*8 FUNCTION GET_DET_LN(REF_PT, GAMMA)
	
		TYPE(POINT2D), INTENT(IN) :: REF_PT
		INTEGER, INTENT(IN) :: GAMMA
	
		TYPE(FUNCTION_2D) :: DIFF_NURBS(2)
	
		CALL GET_DIFF_NURVE_SURFACE_2D(DIFF_NURBS,REF_PT,GEO_KVEC(:),GEO_CTL,1)
	

		IF (GAMMA.EQ.2 .OR. GAMMA.EQ.4 .OR. GAMMA.EQ.6) THEN
! 			PRINT*, DIFF_NURBS(1:2)%VAL(0,1)
			GET_DET_LN = DSQRT(DIFF_NURBS(1)%VAL(0,1)**2 + DIFF_NURBS(2)%VAL(0,1)**2)
		ELSEIF (GAMMA==1 .OR. GAMMA==3 .OR. GAMMA==5) THEN
			GET_DET_LN = DSQRT(DIFF_NURBS(1)%VAL(1,0)**2 + DIFF_NURBS(2)%VAL(1,0)**2)
		ELSE
			PRINT*, 'ERROR - GET_DET_LN : 1'
			STOP
		ENDIF

	END FUNCTION GET_DET_LN
	
	REAL*8 FUNCTION GET_DET_DR(REF_PT, GAMMA_HAT)
	
		TYPE(POINT2D), INTENT(IN) :: REF_PT
		CHARACTER(LEN=1), INTENT(IN) :: GAMMA_HAT
	
		TYPE(FUNCTION_2D) :: DIFF_NURBS(2)
	
		CALL GET_DIFF_NURVE_SURFACE_2D(DIFF_NURBS,REF_PT,GEO_KVEC(:),GEO_CTL,1)
	
		IF (GAMMA_HAT=='B' .OR. GAMMA_HAT=='T') THEN
			GET_DET_DR = DSQRT(DIFF_NURBS(1)%VAL(1,0)**2 + DIFF_NURBS(2)%VAL(1,0)**2)
		ELSEIF (GAMMA_HAT=='L' .OR. GAMMA_HAT=='R') THEN
			GET_DET_DR = DSQRT(DIFF_NURBS(1)%VAL(0,1)**2 + DIFF_NURBS(2)%VAL(0,1)**2)
		ELSE
			PRINT*, 'ERROR - GET_DET_DR : 1'
				STOP
		ENDIF

	END FUNCTION GET_DET_DR

END MODULE PATCH_MAPPING

