	MODULE INTEGRATION

	USE GSQUAD
	USE NURBS_BASIS
	USE LOADFUNCTION

	implicit integer (i-n)
	implicit real(8) (a-h,o-z)

CONTAINS



!------------------INTEGRAL CODE FOR THE STIFFNESS MATRIX ELEMENT--------------
SUBROUTINE GEN_KF(STIF_K, LOAD_F)

	REAL*8, INTENT(OUT) :: STIF_K(DOF, DOF), LOAD_F(DOF)
	TYPE(RECPATCH) :: IRBOX
	TYPE(POINT2D) :: GSPT
	TYPE(INT2D), ALLOCATABLE :: INDX_ROW(:), INDX_COLUMN(:)
	TYPE(MATRIX_22) :: JACOB
	TYPE(FVALUE), ALLOCATABLE :: SF_ROW(:,:), SF_COLUMN(:,:)
	REAL*8, ALLOCATABLE :: WEIGHT(:), LOAD_Q_VEC(:)
	INTEGER :: I,J, II, JJ, KK, GLOBAL_INDX(2), PATCH_ROW, PATCH_COLUMN, PATCHES(2), N
	REAL*8 :: DIFF_XX, DIFF_YY, DIFF_XY, DIFF_YX, DIFF_XN, DIFF_YN, DIFF_NX, DIFF_NY, DIFF_NN, DET_M
	
	STIF_K(:,:) = 0.D0; LOAD_F(:) = 0.D0
	
	PATCH_ROW = 1
	
	!! ---------------------------- [[[[[ OMEGA_HAT(1) VS. OMEGA_HAT(1) ]]]]] ----------------------------
	!! ---------------------------- [[[[[ OMEGA_HAT(2) VS. OMEGA_HAT(2) ]]]]] ----------------------------
	!! ---------------------------- [[[[[ OMEGA_HAT(3) VS. OMEGA_HAT(3) ]]]]] ----------------------------
	DO PATCH_COLUMN = 1, NUMPATCH(2)
	
		IF (USE_ENRICH=='Y' .AND. PATCH_COLUMN==3) THEN
! 			NUMGSPT = 2*(PUORDER + SUM(BS_ORDER(PATCH_ROW, PATCH_COLUMN, :))) + 10
			NUMGSPT = 80
! 			NUMGSPT = 2*(PUORDER + SUM(BS_ORDER(PATCH_ROW, PATCH_COLUMN, :)))
		ELSE 
			NUMGSPT = 2*(PUORDER + SUM(BS_ORDER(PATCH_ROW, PATCH_COLUMN, :)))
		ENDIF
		
		N = NUMGSPT
		
		ALLOCATE(INDX_ROW((BASIS_KVEC(PATCH_ROW, PATCH_COLUMN, 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCH_COLUMN, 2)%POLY_ORDER+1)), &
								SF_ROW(NUMGSPT**2, (BASIS_KVEC(PATCH_ROW, PATCH_COLUMN, 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCH_COLUMN, 2)%POLY_ORDER+1)))
								
		ALLOCATE(GSX(NUMGSPT), GSXW(NUMGSPT), GSY(NUMGSPT), GSYW(NUMGSPT))
		
		ALLOCATE(WEIGHT(NUMGSPT**2), LOAD_Q_VEC(NUMGSPT**2))
								
		DO JJ=1, NUMIR(PATCH_ROW, PATCH_COLUMN, 2)-1
			DO II=1, NUMIR(PATCH_ROW, PATCH_COLUMN, 1)-1
				IRBOX%PT1 = POINT2D(IR_GRID(PATCH_ROW, PATCH_COLUMN, 1,II), IR_GRID(PATCH_ROW, PATCH_COLUMN, 2,JJ))
				IRBOX%PT2 = POINT2D(IR_GRID(PATCH_ROW, PATCH_COLUMN, 1,II+1), IR_GRID(PATCH_ROW, PATCH_COLUMN, 2,JJ))
				IRBOX%PT3 = POINT2D(IR_GRID(PATCH_ROW, PATCH_COLUMN, 1,II+1), IR_GRID(PATCH_ROW, PATCH_COLUMN, 2,JJ+1))
				IRBOX%PT4 = POINT2D(IR_GRID(PATCH_ROW, PATCH_COLUMN, 1,II), IR_GRID(PATCH_ROW, PATCH_COLUMN, 2,JJ+1))
				!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
				CALL GAULEG(IRBOX%PT1%X, IRBOX%PT2%X, GSX, GSXW, NUMGSPT)
				CALL GAULEG(IRBOX%PT1%Y, IRBOX%PT4%Y, GSY, GSYW, NUMGSPT)
				KK = 0
				DO I = 1, NUMGSPT
					DO J = 1, NUMGSPT
						KK = KK + 1
						GSPT = POINT2D(GSX(I), GSY(J))
						JACOB = GET_JACOBIAN_MATRIX(GSPT)
						DET_M = .DETERMINANT.JACOB
						WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
						LOAD_Q_VEC(KK) = LDFT2D(GSPT)
! 							CALL GET_ALL_PHY_BASIS_IN_INT(SF_ROW(KK,:), INDX, GSPT, JACOB)
						CALL GET_PATCHWISE_BS(SF_ROW(KK, :), INDX_ROW(:), GSPT, (/PATCH_ROW, PATCH_COLUMN/), JACOB)
! 							CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF_ROW(KK,:), INDX, DMY_GSPT, JACOB)
					ENDDO
				ENDDO
				!--------------------EVALUATE INTEGRAND AT EACH GAUSS POINT IN SUBMATRIX-----------
				! --------------------- [[[[[ ROW ]]]]] -------------------------------
				DO I = 1, (BASIS_KVEC(PATCH_ROW, PATCH_COLUMN, 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCH_COLUMN, 2)%POLY_ORDER+1)
					DO KK=1, DOF
						IF (NDX(1,KK)==PATCH_ROW .AND. NDX(2,KK)==PATCH_COLUMN .AND. NDX(3,KK).EQ.INDX_ROW(I)%A .AND. NDX(4,KK).EQ.INDX_ROW(I)%B) THEN
							GLOBAL_INDX(1) = KK
							GOTO 111
						ENDIF
					ENDDO
					GLOBAL_INDX(1) = 0
					111 CONTINUE
				!-----------------------------------------------------------------------
				! ------------------- [[[[[ COLUMN ]]]]] -------------------------------
					DO J = 1, (BASIS_KVEC(PATCH_ROW, PATCH_COLUMN, 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCH_COLUMN, 2)%POLY_ORDER+1)
						DO KK=1, DOF
							IF (NDX(1,KK)==PATCH_ROW .AND. NDX(2,KK)==PATCH_COLUMN .AND. NDX(3,KK).EQ.INDX_ROW(J)%A .AND. NDX(4,KK).EQ.INDX_ROW(J)%B) THEN
								GLOBAL_INDX(2) = KK
								GOTO 222
							ENDIF
						ENDDO
						GLOBAL_INDX(2) = 0
						222 CONTINUE
				!-----------------------------------------------------------------------
						IF (PDE=='ELPT' .AND. GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) THEN
						! Poisson
						!-----------------------------------------------------------------------------------------------------------------------------
		! 					DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D00)
							DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D10)
							DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D01)
		! 					DIFF_NX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D10)
		! 					DIFF_NY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D01)
		! 					DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D10)
		! 					DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D01)
							STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + DIFF_XX + DIFF_YY
						!-----------------------------------------------------------------------------------------------------------------------------
						ELSEIF (PDE=='CNVD' .AND. GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) THEN
						! Convection-Diffusion
						!-----------------------------------------------------------------------------------------------------------------------------
	! 						DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D00)
							DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D10)
							DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D01)
		! 					DIFF_NX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), &
		! 																PRODUCT(RESHAPE((/FT_B(:),   SF_ROW(:,J)%D10/), (/N**2, 2/), ORDER=ORDER1), 2))
! 							DIFF_YN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D00)
							DIFF_NY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D01)
		! 					DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D10)
		! 					DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D01)
							
							STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + (EPSLN*(DIFF_XX + DIFF_YY) - DIFF_NY)
		!					STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + (EPSLN*(DIFF_XX + DIFF_YY) - DIFF_NX + 1.5D0*DIFF_NN)
		! 					STIF_K(GLOBAL_INDX(2),GLOBAL_INDX(1)) = STIF_K(GLOBAL_INDX(2),GLOBAL_INDX(1)) + DIFF_XX + DIFF_YY
		! 					STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + ((DIFF_XX + DIFF_YY) + DIFF_NN)
		! 					STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + ((DIFF_XX + DIFF_YY) - DIFF_NX + DIFF_NN)
						!-----------------------------------------------------------------------------------------------------------------------------
						ENDIF
					ENDDO
					DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), LOAD_Q_VEC(:))
					LOAD_F(GLOBAL_INDX(1)) = LOAD_F(GLOBAL_INDX(1)) + DIFF_NN
				ENDDO
			ENDDO
		ENDDO
		DEALLOCATE(INDX_ROW, SF_ROW, GSX, GSY, GSXW, GSYW, WEIGHT, LOAD_Q_VEC)
	ENDDO
	
	
	!! ---------------------------- [[[[[ OMEGA_HAT(1) VS. OMEGA_HAT(2) ]]]]] ----------------------------
	!! ---------------------------- [[[[[ OMEGA_HAT(2) VS. OMEGA_HAT(1) ]]]]] ----------------------------
	
	DO PATCH_COLUMN = 1, 2
	
		IF (PATCH_COLUMN==1) THEN
			PATCHES = (/1, 2/)
		ELSEIF (PATCH_COLUMN==2) THEN
			PATCHES = (/2, 1/)
		ENDIF
	
		NUMGSPT = 2*(PUORDER + SUM(BS_ORDER(PATCH_ROW, PATCH_COLUMN, :)))
		
		N = NUMGSPT
		
		ALLOCATE(INDX_ROW((BASIS_KVEC(PATCH_ROW, PATCHES(1), 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCHES(1), 2)%POLY_ORDER+1)), &
						INDX_COLUMN((BASIS_KVEC(PATCH_ROW, PATCHES(2), 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCHES(2), 2)%POLY_ORDER+1)), &
						SF_ROW(NUMGSPT**2, (BASIS_KVEC(PATCH_ROW, PATCHES(1), 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCHES(1), 2)%POLY_ORDER+1)), &
						SF_COLUMN(NUMGSPT**2, (BASIS_KVEC(PATCH_ROW, PATCHES(2), 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCHES(2), 2)%POLY_ORDER+1)))
		
		ALLOCATE(GSX(NUMGSPT), GSXW(NUMGSPT), GSY(NUMGSPT), GSYW(NUMGSPT))
		
		ALLOCATE(WEIGHT(NUMGSPT**2))
		
		DO JJ=1, NUMIR(PATCH_ROW, PATCH_COLUMN, 2)-1
			DO II=1, NUMIR(PATCH_ROW, PATCH_COLUMN, 1)-1
				IRBOX%PT1 = POINT2D(IR_GRID(PATCH_ROW, PATCH_COLUMN, 1,II), IR_GRID(PATCH_ROW, PATCH_COLUMN, 2,JJ))
				IRBOX%PT2 = POINT2D(IR_GRID(PATCH_ROW, PATCH_COLUMN, 1,II+1), IR_GRID(PATCH_ROW, PATCH_COLUMN, 2,JJ))
				IRBOX%PT3 = POINT2D(IR_GRID(PATCH_ROW, PATCH_COLUMN, 1,II+1), IR_GRID(PATCH_ROW, PATCH_COLUMN, 2,JJ+1))
				IRBOX%PT4 = POINT2D(IR_GRID(PATCH_ROW, PATCH_COLUMN, 1,II), IR_GRID(PATCH_ROW, PATCH_COLUMN, 2,JJ+1))
				!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
				CALL GAULEG(IRBOX%PT1%X, IRBOX%PT2%X, GSX, GSXW, NUMGSPT)
				CALL GAULEG(IRBOX%PT1%Y, IRBOX%PT4%Y, GSY, GSYW, NUMGSPT)
				KK = 0
				DO I = 1, NUMGSPT
					DO J = 1, NUMGSPT
						KK = KK + 1
						GSPT = POINT2D(GSX(I), GSY(J))
						JACOB = GET_JACOBIAN_MATRIX(GSPT)
						DET_M = .DETERMINANT.JACOB
						WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 						LOAD_Q_VEC(KK) = LDFT2D(GSPT)
	! 							CALL GET_ALL_PHY_BASIS_IN_INT(SF_ROW(KK,:), INDX, GSPT, JACOB)
						CALL GET_PATCHWISE_BS(SF_ROW(KK, :), INDX_ROW(:), GSPT, (/PATCH_ROW, PATCHES(1)/), JACOB)
						CALL GET_PATCHWISE_BS(SF_COLUMN(KK, :), INDX_COLUMN(:), GSPT, (/PATCH_ROW, PATCHES(2)/), JACOB)
	! 							CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF_ROW(KK,:), INDX, DMY_GSPT, JACOB)
					ENDDO
				ENDDO
				!--------------------EVALUATE INTEGRAND AT EACH GAUSS POINT IN SUBMATRIX-----------
				! --------------------- [[[[[ ROW ]]]]] -------------------------------
				DO I = 1, (BASIS_KVEC(PATCH_ROW, PATCHES(1), 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCHES(1), 2)%POLY_ORDER+1)
					DO KK=1, DOF
						IF (NDX(1,KK)==PATCH_ROW .AND. NDX(2,KK)==PATCHES(1) .AND. NDX(3,KK).EQ.INDX_ROW(I)%A .AND. NDX(4,KK).EQ.INDX_ROW(I)%B) THEN
							GLOBAL_INDX(1) = KK
							GOTO 333
						ENDIF
					ENDDO
					GLOBAL_INDX(1) = 0
					333 CONTINUE
				!-----------------------------------------------------------------------
				! ------------------- [[[[[ COLUMN ]]]]] -------------------------------
					DO J = 1, (BASIS_KVEC(PATCH_ROW, PATCHES(2), 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCHES(2), 2)%POLY_ORDER+1)
						DO KK=1, DOF
							IF (NDX(1,KK)==PATCH_ROW .AND. NDX(2,KK)==PATCHES(2) .AND. NDX(3,KK).EQ.INDX_COLUMN(J)%A .AND. NDX(4,KK).EQ.INDX_COLUMN(J)%B) THEN
								GLOBAL_INDX(2) = KK
								GOTO 444
							ENDIF
						ENDDO
						GLOBAL_INDX(2) = 0
						444 CONTINUE
				!-----------------------------------------------------------------------
						IF (PDE=='ELPT' .AND. GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) THEN
						! Poisson
						!-----------------------------------------------------------------------------------------------------------------------------
		! 					DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D00)
							DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_COLUMN(:,J)%D10)
							DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_COLUMN(:,J)%D01)
		! 					DIFF_NX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D10)
		! 					DIFF_NY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D01)
		! 					DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D10)
		! 					DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D01)
							STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + DIFF_XX + DIFF_YY
						!-----------------------------------------------------------------------------------------------------------------------------
						ELSEIF (PDE=='CNVD' .AND. GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) THEN
						! Convection-Diffusion
						!-----------------------------------------------------------------------------------------------------------------------------
	! 						DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D00)
							DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_COLUMN(:,J)%D10)
							DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_COLUMN(:,J)%D01)
		! 					DIFF_NX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), &
		! 																PRODUCT(RESHAPE((/FT_B(:),   SF_ROW(:,J)%D10/), (/N**2, 2/), ORDER=ORDER1), 2))
! 							DIFF_YN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_COLUMN(:,J)%D00)
							DIFF_NY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_COLUMN(:,J)%D01)
		! 					DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D10)
		! 					DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D01)
							
							STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + (EPSLN*(DIFF_XX + DIFF_YY) - DIFF_NY)
		!					STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + (EPSLN*(DIFF_XX + DIFF_YY) - DIFF_NX + 1.5D0*DIFF_NN)
		! 					STIF_K(GLOBAL_INDX(2),GLOBAL_INDX(1)) = STIF_K(GLOBAL_INDX(2),GLOBAL_INDX(1)) + DIFF_XX + DIFF_YY
		! 					STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + ((DIFF_XX + DIFF_YY) + DIFF_NN)
		! 					STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + ((DIFF_XX + DIFF_YY) - DIFF_NX + DIFF_NN)
						!-----------------------------------------------------------------------------------------------------------------------------
						ENDIF
					ENDDO
! 					DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), LOAD_Q_VEC(:))
! 					LOAD_F(GLOBAL_INDX(1)) = LOAD_F(GLOBAL_INDX(1)) + DIFF_NN
				ENDDO
			ENDDO
		ENDDO
		DEALLOCATE(INDX_ROW, INDX_COLUMN, SF_ROW, SF_COLUMN, GSX, GSY, GSXW, GSYW, WEIGHT)
	ENDDO
	
	
	!! ---------------------------- [[[[[ OMEGA_HAT(2) VS. OMEGA_HAT(3) ]]]]] ----------------------------
	!! ---------------------------- [[[[[ OMEGA_HAT(3) VS. OMEGA_HAT(2) ]]]]] ----------------------------
	
	DO PATCH_COLUMN = 2, 3
	
		IF (PATCH_COLUMN==2) THEN
			PATCHES = (/2, 3/)
		ELSEIF (PATCH_COLUMN==3) THEN
			PATCHES = (/3, 2/)
		ENDIF
		
		IF (USE_ENRICH=='Y') THEN
! 			NUMGSPT = 2*(PUORDER + SUM(BS_ORDER(PATCH_ROW, PATCH_COLUMN, :))) + 10
			NUMGSPT = 80
		ELSE
			NUMGSPT = 2*(PUORDER + SUM(BS_ORDER(PATCH_ROW, PATCH_COLUMN, :)))
		ENDIF
		
		N = NUMGSPT
		
		ALLOCATE(INDX_ROW((BASIS_KVEC(PATCH_ROW, PATCHES(1), 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCHES(1), 2)%POLY_ORDER+1)), &
						INDX_COLUMN((BASIS_KVEC(PATCH_ROW, PATCHES(2), 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCHES(2), 2)%POLY_ORDER+1)), &
						SF_ROW(NUMGSPT**2, (BASIS_KVEC(PATCH_ROW, PATCHES(1), 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCHES(1), 2)%POLY_ORDER+1)), &
						SF_COLUMN(NUMGSPT**2, (BASIS_KVEC(PATCH_ROW, PATCHES(2), 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCHES(2), 2)%POLY_ORDER+1)))
		
		ALLOCATE(GSX(NUMGSPT), GSXW(NUMGSPT), GSY(NUMGSPT), GSYW(NUMGSPT))
		
		ALLOCATE(WEIGHT(NUMGSPT**2))
		
		DO JJ=1, NUMIR(PATCH_ROW, 3, 2)-1
			DO II=1, NUMIR(PATCH_ROW, 3, 1)-1
				IRBOX%PT1 = POINT2D(IR_GRID(PATCH_ROW, 3, 1,II), IR_GRID(PATCH_ROW, 3, 2,JJ))
				IRBOX%PT2 = POINT2D(IR_GRID(PATCH_ROW, 3, 1,II+1), IR_GRID(PATCH_ROW, 3, 2,JJ))
				IRBOX%PT3 = POINT2D(IR_GRID(PATCH_ROW, 3, 1,II+1), IR_GRID(PATCH_ROW, 3, 2,JJ+1))
				IRBOX%PT4 = POINT2D(IR_GRID(PATCH_ROW, 3, 1,II), IR_GRID(PATCH_ROW, 3, 2,JJ+1))
				!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
				CALL GAULEG(IRBOX%PT1%X, IRBOX%PT2%X, GSX, GSXW, NUMGSPT)
				CALL GAULEG(IRBOX%PT1%Y, IRBOX%PT4%Y, GSY, GSYW, NUMGSPT)
				KK = 0
				DO I = 1, NUMGSPT
					DO J = 1, NUMGSPT
						KK = KK + 1
						GSPT = POINT2D(GSX(I), GSY(J))
						JACOB = GET_JACOBIAN_MATRIX(GSPT)
						DET_M = .DETERMINANT.JACOB
						WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 						LOAD_Q_VEC(KK) = LDFT2D(GSPT)
	! 							CALL GET_ALL_PHY_BASIS_IN_INT(SF_ROW(KK,:), INDX, GSPT, JACOB)
						CALL GET_PATCHWISE_BS(SF_ROW(KK, :), INDX_ROW(:), GSPT, (/PATCH_ROW, PATCHES(1)/), JACOB)
						CALL GET_PATCHWISE_BS(SF_COLUMN(KK, :), INDX_COLUMN(:), GSPT, (/PATCH_ROW, PATCHES(2)/), JACOB)
	! 							CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF_ROW(KK,:), INDX, DMY_GSPT, JACOB)
					ENDDO
				ENDDO
				!--------------------EVALUATE INTEGRAND AT EACH GAUSS POINT IN SUBMATRIX-----------
				! --------------------- [[[[[ ROW ]]]]] -------------------------------
				DO I = 1, (BASIS_KVEC(PATCH_ROW, PATCHES(1), 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCHES(1), 2)%POLY_ORDER+1)
					DO KK=1, DOF
						IF (NDX(1,KK)==PATCH_ROW .AND. NDX(2,KK)==PATCHES(1) .AND. NDX(3,KK).EQ.INDX_ROW(I)%A .AND. NDX(4,KK).EQ.INDX_ROW(I)%B) THEN
							GLOBAL_INDX(1) = KK
							GOTO 555
						ENDIF
					ENDDO
					GLOBAL_INDX(1) = 0
					555 CONTINUE
				!-----------------------------------------------------------------------
				! ------------------- [[[[[ COLUMN ]]]]] -------------------------------
					DO J = 1, (BASIS_KVEC(PATCH_ROW, PATCHES(2), 1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH_ROW, PATCHES(2), 2)%POLY_ORDER+1)
						DO KK=1, DOF
							IF (NDX(1,KK)==PATCH_ROW .AND. NDX(2,KK)==PATCHES(2) .AND. NDX(3,KK).EQ.INDX_COLUMN(J)%A .AND. NDX(4,KK).EQ.INDX_COLUMN(J)%B) THEN
								GLOBAL_INDX(2) = KK
								GOTO 666
							ENDIF
						ENDDO
						GLOBAL_INDX(2) = 0
						666 CONTINUE
				!-----------------------------------------------------------------------
						IF (PDE=='ELPT' .AND. GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) THEN
						! Poisson
						!-----------------------------------------------------------------------------------------------------------------------------
		! 					DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D00)
							DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_COLUMN(:,J)%D10)
							DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_COLUMN(:,J)%D01)
		! 					DIFF_NX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D10)
		! 					DIFF_NY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D01)
		! 					DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D10)
		! 					DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D01)
							STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + DIFF_XX + DIFF_YY
						!-----------------------------------------------------------------------------------------------------------------------------
						ELSEIF (PDE=='CNVD' .AND. GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) THEN
						! Convection-Diffusion
						!-----------------------------------------------------------------------------------------------------------------------------
	! 						DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D00)
							DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_COLUMN(:,J)%D10)
							DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_COLUMN(:,J)%D01)
		! 					DIFF_NX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), &
		! 																PRODUCT(RESHAPE((/FT_B(:),   SF_ROW(:,J)%D10/), (/N**2, 2/), ORDER=ORDER1), 2))
! 							DIFF_YN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_COLUMN(:,J)%D00)
							DIFF_NY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_COLUMN(:,J)%D01)
		! 					DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D01, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D10)
		! 					DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D10, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D01)
								
							STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + (EPSLN*(DIFF_XX + DIFF_YY) - DIFF_NY)
		!					STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + (EPSLN*(DIFF_XX + DIFF_YY) - DIFF_NX + 1.5D0*DIFF_NN)
		! 					STIF_K(GLOBAL_INDX(2),GLOBAL_INDX(1)) = STIF_K(GLOBAL_INDX(2),GLOBAL_INDX(1)) + DIFF_XX + DIFF_YY
		! 					STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + ((DIFF_XX + DIFF_YY) + DIFF_NN)
		! 					STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + ((DIFF_XX + DIFF_YY) - DIFF_NX + DIFF_NN)
						!-----------------------------------------------------------------------------------------------------------------------------
						ENDIF
					ENDDO
! 					DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N**2, 2/), ORDER=ORDER1), 2), LOAD_Q_VEC(:))
! 					LOAD_F(GLOBAL_INDX(1)) = LOAD_F(GLOBAL_INDX(1)) + DIFF_NN
				ENDDO
			ENDDO
		ENDDO
		DEALLOCATE(INDX_ROW, INDX_COLUMN, SF_ROW, SF_COLUMN, GSX, GSY, GSXW, GSYW, WEIGHT)
	ENDDO
	
	
	WRITE(*,*)
	WRITE(*,*) '<<< ASSEMBLE STIFFNESS MATRIX AND LOAD VECTOR : DONE >>>'
	WRITE(*,*)
	
END SUBROUTINE GEN_KF





SUBROUTINE GEN_BD_LN(SUB_K, SUB_F)

	REAL*8, INTENT(OUT) :: SUB_K(BDNDX(1)%LC_NUM, BDNDX(1)%LC_NUM)
	REAL*8, INTENT(OUT) :: SUB_F(BDNDX(1)%LC_NUM)
	
	REAL*8 :: DIFF_NN, DET_M
	REAL*8, ALLOCATABLE :: EXACT_ON_BD(:), WEIGHT(:)
	TYPE(FVALUE), ALLOCATABLE :: SF_ROW(:, :)
	TYPE(INT2D) :: INDX_ROW((BASIS_KVEC(1,3,1)%POLY_ORDER+1)*(BASIS_KVEC(1,3,2)%POLY_ORDER+1))
	TYPE(POINT2D) :: GSPT, DMY_GSPT
	INTEGER :: I, J, II, JJ, KK, N, GLOBAL_INDX(2)
	TYPE(VEC2D) :: SUB_LN
	TYPE(MATRIX_22) :: JACOB
	CHARACTER(LEN=1) :: GAMMA_HAT
	
	IF (USE_ENRICH=='Y') THEN
! 		NUMGSPT = 2*(PUORDER + SUM(BS_ORDER(1, 3, :))) + 10
		NUMGSPT = 80
	ELSE 
		NUMGSPT = 2*(PUORDER + SUM(BS_ORDER(1, 3, :)))
	ENDIF
	
	ALLOCATE(EXACT_ON_BD(NUMGSPT), WEIGHT(NUMGSPT))
	ALLOCATE(SF_ROW(NUMGSPT, (BASIS_KVEC(1,3,1)%POLY_ORDER+1)*(BASIS_KVEC(1,3,2)%POLY_ORDER+1)))
	ALLOCATE(GSX(NUMGSPT), GSXW(NUMGSPT))
	
	N = NUMGSPT; SUB_K(:,:)=0.D0; SUB_F(:) = 0.D0

! !------------------------- LEFT ----------------------------------
! 	DO JJ = 1, NUMIR(2)-1
! 		SUB_LN = VEC2D(POINT2D(0.D0,IR_GRID(2,JJ)), POINT2D(0.D0,IR_GRID(2,JJ+1)))
! 		DIFF_NN = 0.D0
! 		CALL GAULEG(SUB_LN%U%Y, SUB_LN%V%Y, GSY, GSYW, NUMGSPT)
! 		DO I=1,N
! 			GSPT = POINT2D(0.D0, GSY(I))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(GSPT)
! 			DET_M = .DETERMINANT.JACOB
! ! 			GAMMA_HAT = GET_GAMMA_HAT(GSPT)
! ! 			DET_M = GET_DET_DR(GSPT, GAMMA_HAT)
! 			WEIGHT(I) = DET_M*GSYW(I)
! 			CALL GET_ALL_PHY_BASIS_IN_INT(SF_ROW(I,:), INDX, DMY_GSPT, JACOB)
! ! 			CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF_ROW(I,:), INDX, DMY_GSPT, JACOB)
! 			EXACT_ON_BD(I) = EX_DISP(DMY_GSPT)
! 		ENDDO
! ! 		PRINT*, 'HERE-1'
! 		DO I = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
! 			DO KK=1, BDNDX(1)%LC_NUM
! 				IF (BDNDX(KK)%LC_NDX(1).EQ.INDX_ROW(I)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX_ROW(I)%B) THEN
! 					GLOBAL_INDX(1) = KK
! 					GOTO 111
! 				ENDIF
! 			ENDDO
! 			GOTO 112
! ! 			print*, 'here-2'
! 			111 CONTINUE
! 			DO J = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
! 				DO KK=1, BDNDX(1)%LC_NUM
! 					IF (BDNDX(KK)%LC_NDX(1).EQ.INDX_ROW(J)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX_ROW(J)%B) THEN
! 						GLOBAL_INDX(2) = KK
! 						GOTO 222
! 					ENDIF
! 				ENDDO
! 				GOTO 223
! ! 				print*, 'here-3'
! 				222 CONTINUE
! 				DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D00)
! 				SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
! 				223 CONTINUE
! 			ENDDO
! 			
! 			DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:))
! 			SUB_F(GLOBAL_INDX(1)) = SUB_F(GLOBAL_INDX(1)) + DIFF_NN
! 			112 CONTINUE
! 		ENDDO
! ! 		PRINT*, 'HERE-4'
! 	ENDDO
! 
! !------------------------- RIGHT ----------------------------------
! 	DO JJ = 1, NUMIR(2)-1
! 		SUB_LN = VEC2D(POINT2D(1.D0,IR_GRID(2,JJ)), POINT2D(1.D0,IR_GRID(2,JJ+1)))
! 		DIFF_NN = 0.D0
! 		CALL GAULEG(SUB_LN%U%Y, SUB_LN%V%Y, GSY, GSYW, NUMGSPT)
! 		DO I=1,N
! 			GSPT = POINT2D(1.D0, GSY(I))
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(GSPT)
! 			DET_M = .DETERMINANT.JACOB
! ! 			GAMMA_HAT = GET_GAMMA_HAT(GSPT)
! ! 			DET_M = GET_DET_DR(GSPT, GAMMA_HAT)
! 			WEIGHT(I) = DET_M*GSYW(I)
! 			CALL GET_ALL_PHY_BASIS_IN_INT(SF_ROW(I,:), INDX, DMY_GSPT, JACOB)
! ! 			CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF_ROW(I,:), INDX, DMY_GSPT, JACOB)
! 			EXACT_ON_BD(I) = EX_DISP(DMY_GSPT)
! 		ENDDO
! 		DO I = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
! 			DO KK=1, BDNDX(1)%LC_NUM
! 				IF (BDNDX(KK)%LC_NDX(1).EQ.INDX_ROW(I)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX_ROW(I)%B) THEN
! 					GLOBAL_INDX(1) = KK
! 					GOTO 333
! 				ENDIF
! 			ENDDO
! 			GOTO 334
! 			333 CONTINUE
! 			DO J = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
! 				DO KK=1, BDNDX(1)%LC_NUM
! 					IF (BDNDX(KK)%LC_NDX(1).EQ.INDX_ROW(J)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX_ROW(J)%B) THEN
! 						GLOBAL_INDX(2) = KK
! 						GOTO 444
! 					ENDIF
! 				ENDDO
! 				GOTO 445
! 				444 CONTINUE
! 				DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D00)
! 				SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
! 				445 CONTINUE
! 			ENDDO
! 			DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:))
! 			SUB_F(GLOBAL_INDX(1)) = SUB_F(GLOBAL_INDX(1)) + DIFF_NN
! 			334 CONTINUE
! 		ENDDO
! 	ENDDO

!------------------------- BOTTOM ----------------------------------
	DO JJ = 1, NUMIR(1,3,1)-1
		SUB_LN = VEC2D(POINT2D(IR_GRID(1,3,1,JJ),0.D0), POINT2D(IR_GRID(1,3,1,JJ+1),0.D0))
		DIFF_NN = 0.D0
		CALL GAULEG(SUB_LN%U%X, SUB_LN%V%X, GSX, GSXW, NUMGSPT)
		DO I=1,N
			GSPT = POINT2D(GSX(I),0.D0)
			JACOB = GET_JACOBIAN_MATRIX(GSPT)
			DET_M = .DETERMINANT.JACOB
! 			GAMMA_HAT = GET_GAMMA_HAT(GSPT)
! 			DET_M = GET_DET_DR(GSPT, GAMMA_HAT)
			WEIGHT(I) = DET_M*GSXW(I)
			CALL GET_PATCHWISE_BS(SF_ROW(I, :), INDX_ROW(:), GSPT, (/1, 3/), JACOB)
! 			CALL GET_ALL_PHY_BASIS_IN_INT(SF_ROW(I,:), INDX, GSPT, JACOB)
! 			CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF_ROW(I,:), INDX, GSPT, JACOB)
			EXACT_ON_BD(I) = EX_DISP(GSPT)
		ENDDO
		DO I = 1, (BASIS_KVEC(1,3,1)%POLY_ORDER+1)*(BASIS_KVEC(1,3,2)%POLY_ORDER+1)
			DO KK=1, BDNDX(1)%LC_NUM
				IF (BDNDX(KK)%LC_NDX(1)==1 .AND. BDNDX(KK)%LC_NDX(2)==3 .AND. BDNDX(KK)%LC_NDX(3).EQ.INDX_ROW(I)%A .AND. BDNDX(KK)%LC_NDX(4).EQ.INDX_ROW(I)%B) THEN
					GLOBAL_INDX(1) = KK
					GOTO 555
				ENDIF
			ENDDO
			GOTO 556
			555 CONTINUE
			DO J = 1, (BASIS_KVEC(1,3,1)%POLY_ORDER+1)*(BASIS_KVEC(1,3,2)%POLY_ORDER+1)
				DO KK=1, BDNDX(1)%LC_NUM
				IF (BDNDX(KK)%LC_NDX(1)==1 .AND. BDNDX(KK)%LC_NDX(2)==3 .AND. BDNDX(KK)%LC_NDX(3).EQ.INDX_ROW(J)%A .AND. BDNDX(KK)%LC_NDX(4).EQ.INDX_ROW(J)%B) THEN
						GLOBAL_INDX(2) = KK
						GOTO 666
					ENDIF
				ENDDO
				GOTO 667
				666 CONTINUE
				DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D00)
				SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
				667 CONTINUE
			ENDDO
			DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:))
			SUB_F(GLOBAL_INDX(1)) = SUB_F(GLOBAL_INDX(1)) + DIFF_NN
			556 CONTINUE
		ENDDO
	ENDDO
	
	DEALLOCATE(EXACT_ON_BD, WEIGHT)
	DEALLOCATE(SF_ROW)
	DEALLOCATE(GSX, GSXW)
	
! !------------------------- TOP ----------------------------------
! 	DO JJ = 1, NUMIR(1)-1
! 		SUB_LN = VEC2D(POINT2D(IR_GRID(1,JJ),1.D0), POINT2D(IR_GRID(1,JJ+1),1.D0))
! 		DIFF_NN = 0.D0
! 		CALL GAULEG(SUB_LN%U%X, SUB_LN%V%X, GSX, GSXW, NUMGSPT)
! 		DO I=1,N
! 			GSPT = POINT2D(GSX(I),1.D0)
! 			DMY_GSPT = GSPT
! 			JACOB = GET_JACOBIAN_MATRIX(GSPT)
! 			DET_M = .DETERMINANT.JACOB
! ! 			GAMMA_HAT = GET_GAMMA_HAT(GSPT)
! ! 			DET_M = GET_DET_DR(GSPT, GAMMA_HAT)
! 			WEIGHT(I) = DET_M*GSXW(I)
! 			CALL GET_ALL_PHY_BASIS_IN_INT(SF_ROW(I,:), INDX, DMY_GSPT, JACOB)
! ! 			CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF_ROW(I,:), INDX, DMY_GSPT, JACOB)
! 			EXACT_ON_BD(I) = EX_DISP(DMY_GSPT)
! 		ENDDO
! 		DO I = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
! 			DO KK=1, BDNDX(1)%LC_NUM
! 				IF (BDNDX(KK)%LC_NDX(1).EQ.INDX_ROW(I)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX_ROW(I)%B) THEN
! 					GLOBAL_INDX(1) = KK
! 					GOTO 777
! 				ENDIF
! 			ENDDO
! 			GOTO 778
! 			777 CONTINUE
! 			DO J = 1, (BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1)
! 				DO KK=1, BDNDX(1)%LC_NUM
! 					IF (BDNDX(KK)%LC_NDX(1).EQ.INDX_ROW(J)%A .AND. BDNDX(KK)%LC_NDX(2).EQ.INDX_ROW(J)%B) THEN
! 						GLOBAL_INDX(2) = KK
! 						GOTO 888
! 					ENDIF
! 				ENDDO
! 				GOTO 889
! 				888 CONTINUE
! 				DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), SF_ROW(:,J)%D00)
! 				SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
! 				889 CONTINUE
! 			ENDDO
! 			DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF_ROW(:,I)%D00, WEIGHT(:)/), (/N, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:))
! 			SUB_F(GLOBAL_INDX(1)) = SUB_F(GLOBAL_INDX(1)) + DIFF_NN
! 			778 CONTINUE
! 		ENDDO
! 	ENDDO
		
END SUBROUTINE GEN_BD_LN

END MODULE INTEGRATION
