! NAME : HYUNJU KIM
! DATE : 11 / 8 / 2010

MODULE GLBVAR

	USE NEWTYPE

  IMPLICIT NONE

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!   GLOBAL PARAMETER

	REAL(8), PARAMETER :: PI=DACOS(-1.0D0)
	REAL(8), PARAMETER :: DEGREE = PI/180.D0
	REAL(8), PARAMETER:: EPS=5.0D-15
	
	INTEGER, PARAMETER :: PROBLEM = 1
	CHARACTER(LEN=2), PARAMETER :: EQN='FR' ! 'PS' = Poisson,     'FR' = fourth order
	
	REAL*8, PARAMETER  :: ALPHA = 1.60D0
	REAL*8, PARAMETER :: DELTA = 0.050D0
	INTEGER, PARAMETER :: NUMPATCH = 2

	REAL*8 :: PATCHBDPT(NUMPATCH, 2)
	
! 	REAL*8, ALLOCATABLE :: ENRICH_ORDER(:)
	
	! ORDER OF BASIS / PU FUNCTION
	INTEGER ::  PUORDER, BSORDER(NUMPATCH), EXTRA_KNOTS(NUMPATCH)

	!! GLOBAL INDEX WITH BOUNDARY INDEX
	INTEGER :: NUMBS(NUMPATCH), DOF, LC_DOF(NUMPATCH)
	TYPE(BD_INFO) :: BDNDX(MAX_LENGTH)
	
	!!  VARIABLES FOR GEOMETRIC MAP
	TYPE(KNOT_VECTOR) :: PU_KVEC, BS_KVEC(NUMPATCH)
	TYPE(CONTROL_POINTS_2D) :: PU_CTL, BS_CTL(NUMPATCH)
	INTEGER :: PATCH

	!!  CONNECTIVITY ARRAY
	INTEGER, ALLOCATABLE :: CARRAY(:,:)

	!! GREVILLE POINTS (COLLOCATION POINTS)
! 	REAL*8, ALLOCATABLE :: GREV_PT(:)

	!! GAUSS LEGENDRE POINTS (COLLOCATION POINTS)
! 	REAL*8, ALLOCATABLE :: COL_PT(:), COL_W(:),
! 	REAL*8, ALLOCATABLE :: PATCHBDPT(:,:)
! 	INTEGER :: LOC_NUMCOL

	!! GREVILLE / GAUSS POINTS ON BOUNDARY
! 	TYPE(POINT2D), ALLOCATABLE :: BD_COL_PT(:)

	!!  BINOMIAL COEFFICIENTS
	REAL(8) :: BINOM(MAX_DIFF_ORDER,0:MAX_DIFF_ORDER)

	!! LOCAL BASIS INDEX
	INTEGER, ALLOCATABLE :: NDX(:,:)

	!! SUB-LIMITS OF INTEGRAL INDEX
! 	INTEGER, ALLOCATABLE :: SUBIRNDX(:,:,:)
	
		! GAUSS POINTS
	INTEGER :: NUMGSPT
	REAL*8, ALLOCATABLE :: GSPT(:), GSW(:)
	
	REAL*8 :: IR_GRID(NUMPATCH, NUMPATCH, MAX_LENGTH), TMPIR_GRID(NUMPATCH, NUMPATCH,  MAX_LENGTH), INVIR_GRID(NUMPATCH, NUMPATCH, MAX_LENGTH)
	REAL*8 :: L2_GRID( MAX_LENGTH)
	INTEGER :: NUMIR(NUMPATCH, NUMPATCH), TMP_NUMIR(NUMPATCH, NUMPATCH), INV_NUMIR(NUMPATCH, NUMPATCH), L2_NUMIR
	
	
	!! SOLUTION ARRAY IN THE LEAST SQUARE
! 	REAL*8, ALLOCATABLE :: LST_SOL(:)

	CHARACTER(LEN=1) :: CHAR_PUORDER
	CHARACTER(LEN=2) :: CHAR_IORDER
	CHARACTER(LEN=2) :: CHAR_NUMPATCH
	CHARACTER(LEN=1) :: CHAR_PROBLEM
	CHARACTER(LEN=100) :: FILENAME, PUNAME
	
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!	MATERIAL COEFFICIENTS

	INTEGER, DIMENSION(1:2), PARAMETER :: ORDER1=(/ 1, 2 /)
	INTEGER, DIMENSION(1:2), PARAMETER :: ORDER2=(/ 2, 1 /)

	TYPE(POINT2D), PARAMETER :: PT0 = POINT2D(0.D0,0.D0)

END MODULE GLBVAR
