MODULE PLOT

	USE PATCH_MAPPING
	USE GEOMETRY
	USE GSQUAD

	implicit integer (i-n)
	implicit real(8) (a-h,o-z)

CONTAINS

SUBROUTINE PLOTGM()
	
	TYPE(RECPATCH) :: IRBOX
	TYPE(TRANSFORM2D) :: GSPT
	TYPE(POINT2D) :: TSPT, NURBS_PT, NURBS_TSPT
 	TYPE(FUNCTION_1D) :: TS_BS
	INTEGER :: I, J, II, JJ, KK, NI, NJ, NM

	OPEN(1, FILE = './data/irbox')
	OPEN(2, FILE = './data/phyirbox')
	DO JJ=1, NUMIR(2)-1
		DO II=1, NUMIR(1)-1
			IRBOX%PT1 = POINT2D(IR_GRID(1,II), IR_GRID(2,JJ))
			IRBOX%PT2 = POINT2D(IR_GRID(1,II+1), IR_GRID(2,JJ))
			IRBOX%PT3 = POINT2D(IR_GRID(1,II+1), IR_GRID(2,JJ+1))
			IRBOX%PT4 = POINT2D(IR_GRID(1,II), IR_GRID(2,JJ+1))
			WRITE(1, *) IRBOX%PT1
			WRITE(1, *) IRBOX%PT2
			WRITE(1, *) IRBOX%PT3
			WRITE(1, *) IRBOX%PT4
			WRITE(1, *) IRBOX%PT1
			WRITE(1,*)
			WRITE(2, *) GET_POINT_NURVE_SURFACE_2D(IRBOX%PT1,GEO_KVEC,GEO_CTL)
			WRITE(2, *) GET_POINT_NURVE_SURFACE_2D(IRBOX%PT2,GEO_KVEC,GEO_CTL)
			WRITE(2, *) GET_POINT_NURVE_SURFACE_2D(IRBOX%PT3,GEO_KVEC,GEO_CTL)
			WRITE(2, *) GET_POINT_NURVE_SURFACE_2D(IRBOX%PT4,GEO_KVEC,GEO_CTL)
			WRITE(2, *) GET_POINT_NURVE_SURFACE_2D(IRBOX%PT1,GEO_KVEC,GEO_CTL)
			WRITE(2,*)
		ENDDO
	ENDDO
	CLOSE(1)
	CLOSE(2)
	
	OPEN(1, FILE = './data/ndx')
	DO I=1, DOF
		WRITE(1,*) NDX(:,I)
	ENDDO
	CLOSE(1)
	
	OPEN(1, FILE = './data/bdndx')
	DO I=1, BDNDX(1)%LC_NUM
		WRITE(1,*) BDNDX(I)%LC_NDX(:), BDNDX(I)%LC_NUM, BDNDX(I)%GL_NDX
	ENDDO
	CLOSE(1)
	
	OPEN(1, FILE = './data/basis_knot')
	WRITE(1,*) 'POLY_ORDER : ', BASIS_KVEC(1)%POLY_ORDER
	WRITE(1,*) 'LENGTH : ', BASIS_KVEC(1)%LENGTH
	DO I=0, BASIS_KVEC(1)%LENGTH
		WRITE(1,102) BASIS_KVEC(1)%KNOTS(I)
	ENDDO
	WRITE(1,*)
	WRITE(1,*) 'POLY_ORDER : ', BASIS_KVEC(2)%POLY_ORDER
	WRITE(1,*) 'LENGTH : ', BASIS_KVEC(2)%LENGTH
	DO I=0, BASIS_KVEC(2)%LENGTH
		WRITE(1,102) BASIS_KVEC(2)%KNOTS(I)
	ENDDO
	CLOSE(1)

	OPEN(1, FILE = './data/geo_basis_knot')
	WRITE(1,*) 'POLY_ORDER : ', GEO_KVEC(1)%POLY_ORDER
	WRITE(1,*) 'LENGTH : ', GEO_KVEC(1)%LENGTH
	DO I=0, GEO_KVEC(1)%LENGTH
		WRITE(1,102) GEO_KVEC(1)%KNOTS(I)
	ENDDO
	WRITE(1,*)
	WRITE(1,*) 'POLY_ORDER : ', GEO_KVEC(2)%POLY_ORDER
	WRITE(1,*) 'LENGTH : ', GEO_KVEC(2)%LENGTH
	DO I=0, GEO_KVEC(2)%LENGTH
		WRITE(1,102) GEO_KVEC(2)%KNOTS(I)
	ENDDO
	CLOSE(1)

	OPEN(11, FILE = './data/ctl')
	DO I=0, GEO_NUMBS(2)-1
		DO J=0, GEO_NUMBS(1)-1
			WRITE(11,*) GEO_CTL%PTS(J,I,0), GEO_CTL%WGTS(J,I,0)
		ENDDO
		WRITE(11,*)
	ENDDO
	DO J=0, GEO_NUMBS(1)-1
		DO I=0, GEO_NUMBS(2)-1
			WRITE(11,*) GEO_CTL%PTS(J,I,0), GEO_CTL%WGTS(J,I,0)
		ENDDO
		WRITE(11,*)
	ENDDO
	CLOSE(11)

	OPEN(1, FILE = './data/bsplinex')
	OPEN(2, FILE = './data/bspliney')
	DO J=0, NUMBS(1)-1
		DO I=1, 601
			TSPT%X = 1.D0*(I-1)/600.D0
			TS_BS = GET_DIFF_BSPLINE(TSPT%X,BASIS_KVEC(1),J,2)
			WRITE(1,*) TSPT%X, TS_BS%VAL(:)
			TS_BS = GET_DIFF_BSPLINE(TSPT%X,BASIS_KVEC(2),J,2)
			WRITE(2,*) TSPT%X, TS_BS%VAL(:)
		ENDDO
		WRITE(1,*)
		WRITE(2,*)
	ENDDO
	CLOSE(1)
	CLOSE(2)
			
	OPEN(1, FILE = './data/nurbs')
	DO I=1, 101
 		DO J=1, 101
 			TSPT%Y = 1.D0*(I-1)/100.D0
			TSPT%X = 1.D0*(J-1)/100.D0
			NURBS_PT = GET_POINT_NURVE_SURFACE_2D(TSPT,GEO_KVEC,GEO_CTL)
			WRITE(1,*) NURBS_PT
		ENDDO
		WRITE(1,*) 
	ENDDO
	CLOSE(1)

	OPEN(1, FILE = './data/nurbs_bd')
	DO J=1, 101
		TSPT = POINT2D(1.D0*(J-1)/100.D0, 0.D0)
		NURBS_PT = GET_POINT_NURVE_SURFACE_2D(TSPT,GEO_KVEC,GEO_CTL)
		WRITE(1,*) NURBS_PT
	ENDDO
	WRITE(1,*)
	DO J=1, 101
		TSPT = POINT2D(1.D0, 1.D0*(J-1)/100.D0)
		NURBS_PT = GET_POINT_NURVE_SURFACE_2D(TSPT,GEO_KVEC,GEO_CTL)
		WRITE(1,*) NURBS_PT
	ENDDO
	WRITE(1,*)
	DO J=1, 101
		TSPT = POINT2D(1.D0*(J-1)/100.D0, 1.D0)
		NURBS_PT = GET_POINT_NURVE_SURFACE_2D(TSPT,GEO_KVEC,GEO_CTL)
		WRITE(1,*) NURBS_PT
	ENDDO
	WRITE(1,*)
	DO J=1, 101
		TSPT = POINT2D(0.D0, 1.D0*(J-1)/100.D0)
		NURBS_PT = GET_POINT_NURVE_SURFACE_2D(TSPT,GEO_KVEC,GEO_CTL)
		WRITE(1,*) NURBS_PT
	ENDDO
	CLOSE(1)

	102 FORMAT(1000(f20.8,1x))
END SUBROUTINE PLOTGM

END MODULE PLOT
